### ISSUE TITLE
Handle Substrate ws disconnect

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#1]
Figure out a way to handle the websocket disconnect error

* catch the error
* add function to reestablish the connection
* bonus point: expose reconnection meta data. e.g. retrying count

**Comment by ahoseinian** [comment]
this should be fixed in https://github.com/litentry/litentry-app/pull/83. however, there is no automatic reconnection but rather user has to click the button after he has internet again.
if you are happy with it you can close this probably.

**Comment by geastwood** [comment]
Good for now, ty
