### ISSUE TITLE
Feature: Create an account screen

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1000]
> As a user I'd like to have more information on the member I encounter in the app

_[more details.]_
As we already have for members and runners-up of the council, let's have a detailed screen for each account that the user can encounter in the app (technical committee member, proposers of proposals, tips, motions... beneficiary of a tip, voters...)

- [ ] Wireframe:
<img src="https://user-images.githubusercontent.com/85941267/158635870-3559f7cc-04c5-4d3d-9614-85a9c384ab5c.png" width="275" height="600">

- [ ] Copywriting:
* **Screen Title :** TBD we either have the name of the precedent screen (eg: voter ; proposer ...) Or we use `Member` for all the screens wherever the user is coming from
* As we have in the My Account screen, the polka account "logo/image" can be copied
* **Display Name**
* **Account Address**
* **Identity information**
* **Judgment(s)** : all the requested judgments should appear in that section

**Comment by Ekaanth** [comment]
Thanks, @stephanie-olp, for helping me with the list of components that needs to be redirected to member details. Here is a list of the components.

- Democracy proposal proposer (not sure about this one as we don’t have any right now)
-  Council’s member
-  Council’s runner up
-  Voters of council’s member
- Voters of runner up
-  Motion proposer
- Motion voters
- Treasury proposal proposer
- Treasury proposal beneficiary
- Tips proposer
- Tips beneficiary
- Tippers
- Bounty proposer
- Technical committee member
- Crowdlown depositor
