### ISSUE TITLE
Bug: No effect in motions after removing a council account

### ISSUE THREAD

**Issue by ishrak-imam** [litentry/litentry-app#1010]
## Steps To Reproduce

1. Add a council account in the app
2. Go to the motions screen and the Aye/Nay voting buttons are visible
3. Now remove the council screen and go to the motions screen

## The current behaviour
The Aye/Nay vote buttons are still visible

## The expected behaviour
The Aye/Nay vote buttons should not be visible

**Comment by stephanie-olp** [comment]
Done
