### ISSUE TITLE
UI Improvement #6

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#1026]

**Comment by ghost** [comment]
Bounties again. I think its the same as the first one but its a different screen. 

![Screenshot_20220321-114930.jpg](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/6084285e-2c9e-451e-adfc-440873fd67b7)

**Comment by Ekaanth** [comment]
@mikuczi unable to reproduce this UI issue on either of the devices, can you verify if it's the same on the latest version?

<img width="400" alt="Screenshot 2022-03-24 at 9 00 38 AM" src="https://user-images.githubusercontent.com/22363352/159869644-2ba15c3d-283a-4c16-8078-25715946058c.png">

**Comment by Ekaanth** [comment]
Unable to reproduce the issue in the latest version of the app.
