### ISSUE TITLE
Use the new graph endpoints for crowdloan

### ISSUE THREAD

**Issue by ishrak-imam** [litentry/litentry-app#1029]
After https://github.com/litentry/litentry-graph/pull/185 this is merged we have a more systematic way to fetch crowdloans.

Need to integrate this in the app.

- [ ] Once the app is connected to the new graph endpoint create a clean-up ticket in litentry-graph to remove old endpoints

**Comment by Ekaanth** [comment]
This is fixed in the PR https://github.com/litentry/litentry-app/pull/1037
