### ISSUE TITLE
Feature: Migration from react-native-modalize to react-native-bottom-sheet package

### ISSUE THREAD

**Issue by Ekaanth** [litentry/litentry-app#1033]
> As developers, we would like to have a better interactive model
> Migrate to the package that is actively managed

### Acceptance criteria:

- [ ]  Migrating to the actively managed model package
- [ ]  Able to provide a better model experience for the users.

### Suggested 

We can look into react-native packages actively managed for model-related features. `react-native-bottom-sheet` looks promising, as @ishrak-imam suggested. We can conduct research to look for any new favorable packages if available.

- [x] Package picked from the research.
- [x] Package replacing the existing  `react-native-modalize`.

**Comment by Ekaanth** [comment]
Like @ishrak-imam suggested, [react-native-bottom-sheet](https://gorhom.github.io/react-native-bottom-sheet/) is actively managed with a decent downloaded package to go ahead.

**Comment by silva-fj** [comment]
> We are creating new screens to bring up a model. The backdrop functionality isn't available if we define a model on the same screen.

I'm not sure I understand this.

We should be able to implement what we need with the current library (`react-native-bottom-sheet` uses the same approach to manage the modals), we just need to change the way we use it. I don't think this issue justifies changing the library.

Having said that, I do prefer `react-native-bottom-sheet`

**Comment by Ekaanth** [comment]
@franjs When I created it, I had limited knowledge of this issue. Yes, when I read about this issue, it is wrong. Since we were using the model to render in the new page, that is how I assumed it worked. Now that I realize the issue is being modified to migrate to `react-native-bottom-sheet` for a better user experience.

**Comment by Ekaanth** [comment]
Until we finalize the right UI/UX way of showing a model this issue will be blocked.

**Comment by Ekaanth** [comment]
Amazing work from @ishrak-imam An initial test case was created for network selection as a prof of concept ref: https://github.com/litentry/litentry-app/pull/1094
