### ISSUE TITLE
Bug: Investigate drawer(s) not responding 

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1058]

**Comment by Ekaanth** [comment]
I was able to reproduce this issue 
Here is how the issue looks like:

https://user-images.githubusercontent.com/22363352/163831532-3893f52c-ba4f-442f-bab7-b3b40210040b.mp4

**Comment by stephanie-olp** [comment]
Investigate if it's a issue with the library or how we are handling the navigation state
