### ISSUE TITLE
Feature: Crowdloan Leaderboad in the app

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1080]
- [ ] Investigate which data are available and can be fetched from Web3Go (Litentry graph?)
- [ ] Pick data that we want to display 
- [ ] Create Screen Mockup

**Comment by geastwood** [comment]
My understanding is, this feature is information-hierarchy-wise can be depicted as
```
Crowdloan
 -- particular parachain
    -- crowdloan leaderboard
```

I does seem to provide much value for the user now. This feature can be planed and scoped when we are focusing on expending functionalities of crowdloan related features.
