### ISSUE TITLE
New governance mechanism tasks list

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1103]
## Intro
Soon (don't have a date yet), a new governance mechanism will be implemented on Kusama first, then on Polkadot. 
Our goal is to be ready for these changes and reflect them in our app as soon as there are effective.
More information about this new mechanism [here](https://www.notion.so/litentry/Governance-Sync-with-Raul-12-04-2022-0c045466267743f98be10a1a51ee3be6)

### Minimal implementation to support the new mechanism
- [ ] Create different tracks in democracy (for both ongoing referenda & waiting queues)
- How many? 
- Which ones?
(Answers will be given by the Parity Team)
- [ ] Remove Council and Technical Committee
- [ ] Create a tab for the Substrate Fellowship (SF) with the feature for them to vote for proposal whitelisting
- [ ] Create a section to see who is part of the SF 

### Data that has to be fetched in the Litentry Graph
- _list of mandatory_
- _list of nice to have_

### How do we support both systems (the old and the new one) at the same one? 

- [ ] Develop this future mechanism while still maintaining the current one : 
- [ ] This mechanism will be first tested on Kusama, which means that at a certain point in time Kusama and Polkadot will have different governance mechanisms: how should handle this situation

###  Other important tasks/implementations

- [ ] A new wireflow for the app to match the new mechanism 
- [ ] Rebranding (new name, new design...) 
- [ ] Redesign: the combination of the new mechanism + rebranding +  new design system? 
- [ ] Education material (within the app + collaboration with Parity
- [ ] Promote app to production

**Comment by stephanie-olp** [comment]
Questions for Parity :
- If a user delegates his voting power to someone else what happens when there is a conflict between the delegate and the user? 
- Can delegate second for someone else?

**Comment by stephanie-olp** [comment]
Next Step:
* Look deeper into the new mechanism 
* Coming up with some User flow options

**Comment by ishrak-imam** [comment]
Move it to notion and close it @mikuczi

**Comment by luisjborges** [comment]
Moved it to notion => https://www.notion.so/litentry/New-governance-mechanism-tasks-list-11b1bdf0f998412086c5f9ed305298cf

And Asana => https://app.asana.com/0/1202739194556156/1202777006572012/f

Proceeding to close the ticket @mikuczi @ishrak-imam
