### ISSUE TITLE
Bug: 🐛 Litentry still shown under ongoing crowdloan (projects in general)

### ISSUE THREAD

**Issue by Ekaanth** [litentry/litentry-app#1120]
## Steps To Reproduce

1. Go to app settings and clear the app cache and data
2. Navigate to the app and click on crowdloan from the drawer menu
3. Litentry project is still visible.

Link or media file of the bug:

<Img src="https://user-images.githubusercontent.com/22363352/165894891-3f7f3802-07e4-4818-8e03-faf445c250ef.png" width="250"/>

## The expected behavior

Litentry should be shown in completed instead its shown in the ongoing section.

**Comment by stephanie-olp** [comment]
Not something we can fix from our side
