### ISSUE TITLE
Decide on the account view in the app

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1122]
4 options:
- No address view: current state
- One app account to which user can link his different addresses (e.g: PolkAssembly)
- A unique address view: The user can switch from one account to another and the respective data will be shown (e.g: Instagram)
- Multiple account view: Aggregated data of the different addresses

**Comment by stephanie-olp** [comment]
https://www.notion.so/litentry/Account-in-the-App-2235d4089580429cbb12c205c074e784

**Comment by silva-fj** [comment]
@stephanie-olp The notion page is not public

**Comment by stephanie-olp** [comment]
My bad, should work now :)
