### ISSUE TITLE
How do we handle the network change ? 

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1148]
Currently, apart from the dashboard, the user doesn't have information on which network he is.

With the future cohabitation of the old and the new governance, a clear distinguishment between the different networks is even more important. 

How do we use the UI/UX to distinguish the different networks ?

**Comment by stephanie-olp** [comment]
Part of the navigation discussion

**Comment by ghost** [comment]
wWhat are the variants? 

Old Gov vs New Government

Different menu items

Which projects are changing to new gov? when the change will take place?

**Comment by ghost** [comment]
We can have swap like aribnb experience from Host to Traveling

**Comment by stephanie-olp** [comment]
When the new governance will be implemented only on Kusama it will be in fact new governance on Kusama vs Old governance on Polkadot. We haven't got an exact date on the implementation of the new governance, just that it should happen before the end of the 1st semester of 2022. 
Moreover, we might also have the Litmus network in the app quite soon. So more generally we need something that clearly differentiate the switch from one ecosystem to another one

**Comment by luisjborges** [comment]
@mikuczi What do you think about this issue? 
- Is this something you are working already?
- Should this be moved and followed up in Asana?

Thanks!
