### ISSUE TITLE
Add past democracy proposals

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1173]
As a user I want to access not only the ongoing proposals but also the past ones

The past proposals should be accessible from the democracy screen

⚠️ what do we need?
 UI/UX : How do we change the Democracy screen to display the past proposals

**Comment by stephanie-olp** [comment]
Data that need to be indexed
* Proposal ID
* Title of the proposal (if there is one)
* Type of action (module)
* Proposal Description (if there is one)
* Date of creation
* Date of last update
* Proposal author
* Proposal status/ Execution Result
* Outcome Prediction (nb of aye & nye)
* Voting details (who voted what)

**Comment by stephanie-olp** [comment]
Will need to change the current democracy screen to display both the ongoing and past proposals.
My original idea was just to use a filter feature

**Comment by silva-fj** [comment]
Fetch the proposals from the indexer and display the title in the teaser and both title and description in the detail screen (create a detail screen and remove the link to polkassembly

**Comment by geastwood** [comment]
> Fetch the proposals from the indexer and display the title in the teaser and both title and description in the detail screen (create a detail screen and remove the link to polkassembly

Is this the new plan?

**Comment by silva-fj** [comment]
No, we are still waiting for the designs. We just want to have the data already available
