### ISSUE TITLE
Feature: Proposal timeline

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1176]
> As a user, I'd like to know at which stage of the process a particular proposal is_ 

Each proposal will have a timeline, a timeline that we’ll indicate to the user the current step but also the different steps that the proposal has already been through, e.g: in the waiting list, currently going through referenda ...

The timeline will be accessible through a button on the proposal detailed screen:
<img src="https://images.zenhubusercontent.com/61029ef6db52052cb2a2578a/9fd5a2d4-661f-43d9-84c7-eb3b60ac8583" width="275" height="600">

On this different screen, the user will land on the ongoing step but can swipe left to see the previous step(s)

**Comment by stephanie-olp** [comment]
Which are the possible different steps?

**Comment by stephanie-olp** [comment]
https://www.notion.so/litentry/Timeline-12fc5c0ef2b54d979302a6b3025e64e6

**Comment by ishrak-imam** [comment]
@mikuczi please add mockup.

**Comment by ghost** [comment]
![Screenshot 2022-08-10 at 14.40.53.png](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/1e7c415f-0236-4bcb-896c-98882e024ac8
