### ISSUE TITLE
Bug: External links not clickable in tips detailed screen

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1177]
On Android

## Steps To Reproduce

1. Go to the Tips section in Treasury
2. Open the detailed screen of one tip that has an external link in the "reason" field (e.g: a link to a youtube video, or polkassembly)
3. Try to click on that link

Link or media file of the bug:

## The current behavior

The link is blue, so appears as clickable but when we click on it nothing happens

## The expected behavior
When clicking on the link user should be redirected

**Comment by stephanie-olp** [comment]
More information need to be added

**Comment by stephanie-olp** [comment]
@franjs FYI 
Video recording of the issue:
https://images.zenhubusercontent.com/315463277/e998fdd3-54a0-4928-afc0-09d757b9c169/screen_recording_20220513_144636_litentry.mp4
on Android 11, Samsung S21 FE

**Comment by stephanie-olp** [comment]
Don't know if it's the same issue but also have the problem with PolkAssembly link (works from the detailed screen but not on the overview screen):
https://images.zenhubusercontent.com/315463277/b0479e0f-bb9d-48cd-b00d-f13de75a00fd/screen_recording_20220513_144901_litentry.mp4

**Comment by stephanie-olp** [comment]
Don't know if it's the same issue but also have the problem with PolkAssembly link (works from the detailed screen but not on the overview screen):
https://images.zenhubusercontent.com/315463277/b0479e0f-bb9d-48cd-b00d-f13de75a00fd/screen_recording_20220513_144901_litentry.mp4

**Comment by stephanie-olp** [comment]
Don't know if it's the same issue but also have the problem with PolkAssembly link (works from the detailed screen but not on the overview screen):
https://images.zenhubusercontent.com/315463277/b0479e0f-bb9d-48cd-b00d-f13de75a00fd/screen_recording_20220513_144901_litentry.mp4

**Comment by silva-fj** [comment]
Thank you @stephanie-olp, we will take a look.
