### ISSUE TITLE
Redesign the proposals content

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1204]
Offer a clearer content for the user with only information that will help him understand the proposal

**Comment by ishrak-imam** [comment]
@mikuczi please add mockup

**Comment by ghost** [comment]
![Council Motion.png](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/589a9af0-156a-4d9f-9bec-4e315a772979)

**Comment by ghost** [comment]
not final but just a reference
