### ISSUE TITLE
Add past tips

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1209]
> As a user I want to access the past tips

The past tips should be accessible from the treasury screen

### ⚠️ what do we need?

- [ ] UI/UX : How do we change the Treasury screen to display the past proposals
- [ ] Index: Which data has to be indexed ?

**Comment by stephanie-olp** [comment]
Data that needs to be indexed:
* Tip Beneficiary
* Tip Finder (the person who suggested the tip)
* Reason
* Status
* Amount of the reward/tip
* List of tippers with value of tip

**Comment by silva-fj** [comment]
Order the list by date and add infinite scrolling

**Comment by geastwood** [comment]
I thought the tip data are already being indexed, does this mean we need to reindex the tips?

**Comment by ishrak-imam** [comment]
> I thought the tip data are already being indexed, does this mean we need to reindex the tips?

We don't have to reindex tips. This ticket is to include the past tips in the app. Currently we only show the active/open ones.
