### ISSUE TITLE
Feature: enhance view on display the raw transaction

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#122]
> As **User** I'd like to know the payload I'm authorizing before starting the signing process and be provided with more information.

### ⚠️ what do we need?

- [ ] UI/UX 
- [ ] Copywriting

### Acceptance criteria:

- [x] Before user being presented to `sign` the tx, user can have a preview of the raw payload
- [x] when click `sign`, user will be presented with the `QR` code, what the app currently has
- [x] the raw payload is collapsed first, only expend with user interaction
- [x] user get an estimate on fees (see screenshot)

### Detailed Description (if necessary)
- _[...]_

### implementation details (if necessary)
* Collapse the detail payload first
* Enhance the current HOC to be able to pass additional `tx` payload to present the payload
* Possibly need a mapping for `module.methodName` <=> brief description

<img width="1123" alt="Screenshot 2021-06-11 at 02 33 29" src="https://user-images.githubusercontent.com/1623359/121614028-1865e680-ca5e-11eb-876f-4f973fcd5d80.png">

**Comment by ahoseinian** [comment]
Waiting for UI/UX design.
