### ISSUE TITLE
Milestone 2 | Push Notifications | Proposals

### ISSUE THREAD

**Issue by lmdobreva** [litentry/litentry-app#124]
As a user, I want to receive push notifications when:

- New proposal available
- Proposal approved
- Proposal rejected
- Proposal cancelled
- Reminders?

Question:
I assume we need to distinguish between the different proposal types?

**Comment by stephanie-olp** [comment]
I'm closing this issue as we have the following Notion page:  https://www.notion.so/litentry/Push-Notifications-f21647e48a4f41689e29d4556fd6caf3

**Comment by stephanie-olp** [comment]
I'm closing this issue as we have the following Notion page:  https://www.notion.so/litentry/Push-Notifications-f21647e48a4f41689e29d4556fd6caf3
