### ISSUE TITLE
Milestone 2 | Push notifications | General push notification settings

### ISSUE THREAD

**Issue by lmdobreva** [litentry/litentry-app#125]
As a user, I want to be able to set my settings in regards to push notifications:

- General on/off

Per topic:
-- New proposals available
-- Proposal approved
-- Proposal rejected
-- Proposal cancelled
-- Reminders?

Per role:
-- Councillors
-- Treasury member
-- Technical committee member
-- General voter
-- What other roles are there?

**Comment by stephanie-olp** [comment]
Hey @lmdobreva is it okay if I close this issue ? I can later create a ticket for PN per role

**Comment by lmdobreva** [comment]
yep, close it
