### ISSUE TITLE
Bug: JSON parse error at firebaseConfig.

### ISSUE THREAD

**Issue by Ekaanth** [litentry/litentry-app#1284]
For the first time, trying to install the app and running it on an emulator encounters an error `JSON Parse error: Unexpected EOF` ar firebaseconfig.ts.

## Steps To Reproduce

1. Uninstall the application
2. Run `yarn android` after the build. It runs into the error.

Link or media file of the bug:
<img src="https://user-images.githubusercontent.com/22363352/176383008-5aa27531-03af-4c11-b896-8a4a12bfc550.png" width="250" />

## The behavior
If the application is closed( removed from background running) and then opened up the app, it works smoothly.

**Comment by ishrak-imam** [comment]
This is not reproducible from my side. If anyone can reproduce it please ping me.

**Comment by silva-fj** [comment]
> This is not reproducible from my side. If anyone can reproduce it please ping me.

@ishrak-imam I was able to reproduce it with a fresh install on android:

- Remove the app from the device/emulator
- Build the app again
- You should see the error the first time you open the app
