### ISSUE TITLE
Get indexed referendas from the litentry graph

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#1289]
[Here](https://graph.litentry.io/graphql?query=query%20MyQuery%20%7B%0A%20%20substrateDemocracyReferendas%20%7B%0A%20%20%20%20id%2C%0A%20%20%20%20democracyProposal%20%7B%0A%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20proposalHash%2C%0A%20%20%20%20%20%20status%2C%0A%20%20%20%20%20%20depositAmount%2C%0A%20%20%20%20%20%20updatedAt%2C%0A%20%20%20%20%20%20date%2C%0A%20%20%20%20%20%20seconds%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) is an example the query available.

- [ ] Check the integrity of the data. (If it's already good enough to consume it).
- [ ] Refactor the app to fetch the indexed data.
- [ ] Add pagination to the list (Infinite scrolling).

**Comment by ishrak-imam** [comment]
I believe this is already done here https://github.com/litentry/litentry-app/pull/1314
