### ISSUE TITLE
Create Demo App to profile Crypto functions

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#1302]
Create a brand new app to demo the issues with the polkadot libraries:

- Create a new react native app (or expo).
- Install and configure polkadot/api and polkadot/keyring (ui-keyring).
- Display a button to generate a mnemonic phrase and display the mnemonic phrase in a Text.
- Create a second screen and display chain info (from the polkadot api).

With this app we should be able to profile the issues with the crypto functions.

**Comment by Ekaanth** [comment]
I have created a new demo application which can be found on https://github.com/Ekaanth/keyringApp I have invited @franjs and @ishrak-imam to the project as collaborators.

**Comment by Ekaanth** [comment]
A demo app has been set up and is ready to be used, the app can be found here: https://github.com/Ekaanth/keyringApp
