### ISSUE TITLE
Add polling + pull to refresh on motions and referendums

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#1315]
Since we are not using subscriptions to get the data from the chain, we need to make a more aggressive strategy to fetch data as it gets outdated quite easily.

**Comment by Ekaanth** [comment]
Would the data be indexed as soon as the transaction is made? Currently, as soon as the transaction is carried out, the refetch is invoked and that refetch is obtained from the graph.

**Comment by silva-fj** [comment]
> Would the data be indexed as soon as the transaction is made? Currently, as soon as the transaction is carried out, the refetch is invoked and that refetch is obtained from the graph.

Normally it takes a few seconds to be indexed, but this is not related to refetching data after sending transactions
