### ISSUE TITLE
Bug: unable to reconnect to the web socket.

### ISSUE THREAD

**Issue by Ekaanth** [litentry/litentry-app#1328]
## Steps To Reproduce

1. Turn off the internet connection data and we see the globe in `Network switch` being disabled
2. Turn on the internet connection, The globe is still disabled.

Link or media file of the bug:

<Img src="https://user-images.githubusercontent.com/22363352/182624946-902a31d2-1fbc-45ed-9b32-72803d42fe5b.gif" width="250" />

## The expected behavior
The WebSocket has to reconnect and the globe has to go back to normal.

**Comment by silva-fj** [comment]
I wonder if this is an issue on android only, I cannot reproduce it on IOS. The behaviour I get is: It takes some time for the api to detect it is not connected, but after connecting the device to the internet again the api gets connected almost instantly

**Comment by Ekaanth** [comment]
> I wonder if this is an issue on android only, I cannot reproduce it on IOS. The behaviour I get is: It takes some time for the api to detect it is not connected, but after connecting the device to the internet again the api gets connected almost instantly

was unable verify it on IOS since mocking the network disconnection on the emulator was not possible.

**Comment by silva-fj** [comment]
> > I wonder if this is an issue on android only, I cannot reproduce it on IOS. The behaviour I get is: It takes some time for the api to detect it is not connected, but after connecting the device to the internet again the api gets connected almost instantly
> 
> was unable verify it on IOS since mocking the network disconnection on the emulator was not possible.

Another way to do it is to disconnect your mac from the internet, the simulator will also disconnect

**Comment by ishrak-imam** [comment]
I think we have to make the `useInitApi` hook listen for network state changes and act accordingly.

**Comment by silva-fj** [comment]
> I think we have to make the `useInitApi` hook listen for network state changes and act accordingly.

By network state changes do you mean the device internet connection state? The Polkadot API "handles" this already.. We should check if this is a specific issue on android, as on IOS it works good enough

**Comment by Ekaanth** [comment]
I encountered another issue while working on it: the globe is not off even if we don't have internet.
<img src="https://user-images.githubusercontent.com/22363352/185079623-4e3b9bbc-3645-4c1a-b3e6-3c800a70b076.gif" width="250" />
