### ISSUE TITLE
Bug: Unable to refetch the data when fetching from graph fails

### ISSUE THREAD

**Issue by Ekaanth** [litentry/litentry-app#1330]
## Steps To Reproduce

1. Turn off the internet connection, and we see the data that was fetching fails
2. on reconnecting to the internet, the re-fetching of data isn't happening.
3. only after refreshing the app does the data seem to be loading.

Link or media file of the bug:
<img src="https://user-images.githubusercontent.com/22363352/182629687-86da3c88-0926-46eb-a5fa-5c41c6898a4a.gif" width="250" />

## The expected behavior
The application data needs to be fetched as soon as the mobile is connected to the internet.

**Comment by silva-fj** [comment]
This is not exactly a bug, as we’ve never implemented it. We can add a retry mechanism to handle this 👍🏼

**Comment by Ekaanth** [comment]
Blocked by https://github.com/litentry/litentry-app/pull/1327
