### ISSUE TITLE
Stabilize tests

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#1331]
It seems that some tests are failing when running all tests but they pass when running alone. Also as part of setting up the new theme, we have skipped a few tests to separate the work (as the tests failing have no relation with the changes). Only a couple of tests are failing due to using `material-top-tabs`, they should be fine once we upgrade `react-native-paper-tabs`

**Comment by Ekaanth** [comment]
On the latest develop branch I'm not able to reproduce this issue, despite running `yarn test` several times, is there something I'm missing or the test cases are failing with the setup of the new theme?

**Comment by silva-fj** [comment]
It is in the branch for the new theme, this issue is just to track it and fix them in a separate PR as that one is already too big.

**Comment by silva-fj** [comment]
For reference: https://github.com/litentry/litentry-app/pull/1325/commits/5da20952d92af1b75b2eaa0b6c0d4febc96500c6

**Comment by silva-fj** [comment]
It can to be done after https://github.com/litentry/litentry-app/pull/1325 is merged

**Comment by Ekaanth** [comment]
We need to also make a test case fix for flashlist when this PR is merged.https://github.com/litentry/litentry-app/pull/1332
