### ISSUE TITLE
Bug: App crashed when clicked on Prime Voter

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#1334]
App version:

## Steps To Reproduce

1. Navigate to the council
2. Click on Prime Voter

Link or media file of the bug:

## The current behavior
App crash

## The expected behavior
Should not crash

https://user-images.githubusercontent.com/1623359/184658396-6562a045-0f97-4c7a-b0c6-337f15b3f4ee.mp4

**Comment by luisjborges** [comment]
Bug reported and followed up in our new Asana Sprint board => https://app.asana.com/0/1202764086163080/1202804387617972/f

@geastwood For the following bug reporting, please use the Asana board and add a bug using the "Bug Template". The prioritization will be done accordingly once the ticket is in the board. Thanks!

![bug_template](https://user-images.githubusercontent.com/46839918/184801841-aa4692f2-61e3-4697-893a-d4ed990ae6ca.png)
