### ISSUE TITLE
Bug: Infinite refresh when offline on the Democracy screen

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#1335]
App version:

## Steps To Reproduce

1. Navigate to the Democracy screen

Link or media file of the bug:

https://user-images.githubusercontent.com/1623359/184659397-c84b6be3-fc1b-4f21-a8aa-03e4a89dd849.mov

## The current behavior
Infinite refresh

## The expected behavior
Should not trigger an infinite refresh

**Comment by luisjborges** [comment]
Bug reported and followed up in our new Asana Sprint board => https://app.asana.com/0/1202764086163080/1202804387617977/f
