### ISSUE TITLE
Spike: Push notification infra under Firebase

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#137]
To be added by @geastwood

* replace local queue with Firebase infra
* store user preference in Firebase
* ...

**Comment by silva-fj** [comment]
It is possible to rely completely on the Firebase infra to send push notifications to multiple devices (making use of FCM topic messaging). This would be a good start for adding basic support for push notifications, later we can add more use cases for push notifications targeted to specific accounts (for this type of push notifications we do need to store device tokens and probably have our own queue.

Docs:
https://rnfirebase.io/messaging/usage#topics
https://rnfirebase.io/messaging/server-integration#send-messages-to-topics

**Comment by franjs** [comment]
@geastwood

**Comment by geastwood** [comment]
Question 1:
If there are two types of PN, A and B, If a user only interested in receiving PN A and not B. This logic would in theory still live in our server? I.E. we determine only to ask firebase to send A to device and not B



Question 2:

I can imagine that user record can live on firebase storage (like device token, subscription pref.) However when the event from on chain is captured from our service, we have to query the firebase storage for all relevant users device token and send out the PNs?

**Comment by geastwood** [comment]
After browsing the _topic_ doc a bit, I do see that using _topic_ can let the client, namely user device to host the logic of PN, namely if user want to subscribe on chain event A, but not B, we can just instantiate _topic A'_ (which corresponds to A)

That means we can transfer a set of config into a bunch of PubSubs

Would this also fit your understanding? @franjs

**Comment by silva-fj** [comment]
@geastwood Yes, the user decides what topics to subscribe to (A and B) on the app. Our service listens to chain events and sends messages to firebase for the topics we configure (A, B, C, etc) and firebase will send notifications to all devices that have subscribed to those topics. 

We just need to configure in our service the events we want to listen and list them on the app so the users can subscribe to them.

**Comment by geastwood** [comment]
I think we can close this issue @franjs

**Comment by silva-fj** [comment]
No longer relevant, we are already using firebase.
