### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#140]
Currently the app does not have a Splash screen, so when launching the app a white screen is displayed for a brief moment.

This library offers an easy way to set everything up: https://github.com/zoontek/react-native-bootsplash 

@geastwood, @lmdobreva  can any of you coordinate with design to get an image for this?

**Comment by geastwood** [comment]
Providing a PNG will be enough? @franjs

**Comment by silva-fj** [comment]
> Providing a PNG will be enough? @franjs

I think so, yes.
