### ISSUE TITLE
Push Permissions

### ISSUE THREAD

**Issue by ahoseinian** [litentry/litentry-app#160]
## things to clarify
- [x] (on IOS) when should we ask the user to allow permission, on the first app start?
- [x] if the user declines it should we ask him to enable it again when he/she tries to change notification settings?
- [x] should we show the user the warning for enabling their push notification on both platforms?

### related discussion
> Yes I know what you mean.. What I was referring to is that on IOS the user won't get PN until it manually approves the permissions, so if the user by mistake declines the permissions (the prompt we have) the message makes sense because it helps to know where to enable it again.. that's not the case on android, so with this message a user could think that for the PN to work he/she needs to go to the settings and enable it manually

_Originally posted by @franjs in https://github.com/litentry/litentry-app/pull/156#discussion_r657979679_

**Comment by ahoseinian** [comment]
@stephanie-olp could you answer the clarification part of this issue?

**Comment by stephanie-olp** [comment]
1/ For iOS users we should show the following prompt permission when the user download and open the app for the 1st time:
![image](https://user-images.githubusercontent.com/85941267/123281764-3cb7cd80-d50a-11eb-87fc-efcfb8caaba9.png)
If they accept, we show them the native permission to send Push Notifications.
That will allow us to ask him more than once.

2/ If they want to enable PN after they declined the native permission, the information message on the PN setting screen should explain them how to enable it. I'll edit the current message to make it clearer.

3/ As Francisco said we don't need Android users permission to send them notifications and that message can be misunderstood. If an Android user had previously manually disable PN in his device settings, he'll certainly know how to enable it again. So showing this message to iOS users should be enough

**Comment by stephanie-olp** [comment]
I don't know how complicated it would be for the prompt permission to be implemented. If you want for now we can skip it and directly goes with the native permission. What do you think? @franjs @ahoseinian

**Comment by geastwood** [comment]
Is this one already merged?

**Comment by ahoseinian** [comment]
yes I think I messed up the pull request linking https://github.com/litentry/litentry-app/pull/167
