### ISSUE TITLE
Auto build branch on PR

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#178]
Here is the suggestion that we can trigger `Bitrise` build on PR.

The benefits are obvious
* people can really test on the branch before merging
* a complete build test would somewhat prove nothing seriously went wrong.
* etc

Drawbacks
* potentially costly
* too heavy for small PR

PS, have to regex the PR title to exclude the bumping version PR

**Comment by geastwood** [comment]
@ahoseinian @franjs what do you guys think? 

Probably is too much at the beginning?

**Comment by silva-fj** [comment]
I think it would be nice to have, but we can wait a bit more to implement it

**Comment by ahoseinian** [comment]
I think let's keep this in the backlog for now and let's revisit it when we make the first stable version of the app. after that we can be more meticulous with testing on device before merging to dev.
