### ISSUE TITLE
Integrate Beacon SDK into the app

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#192]
* [ ] able to compile on iOS
* [ ] able to compile on Android
* [ ] very basic call

Base on the talk with Beacon Team, they mentioned the libsodium.wasm will possibly block us from integrating it.

PS. this integration only means install beacon sdk (TypeScript) as package (not wrap beacon sdk within a WebView).

**Comment by geastwood** [comment]
@ahoseinian Let's log some of the findings here.

**Comment by ahoseinian** [comment]
@geastwood as we already discussed with @AndreasGassmann the [libsodium](https://github.com/jedisct1/libsodium.js) package is the problem

It is not working because of missing modules in react native env like (path, fs, crypto):
- https://github.com/jedisct1/libsodium.js/issues/245
- https://github.com/jedisct1/libsodium.js/issues/86#issuecomment-290923176


# Solutions:

#### 1. Forking beacon sdk and replace libsodium

We could see if this hack works:
- https://github.com/jedisct1/libsodium.js/issues/202#issuecomment-649390377
- https://github.com/jedisct1/libsodium.js/issues/202#issuecomment-706714847  (so the hack would only work on a certain version https://github.com/jedisct1/libsodium.js/issues/249) 

Or alternatively we could replace the libsodium with one of:
- https://github.com/mvayngrib/react-native-crypto 
- https://github.com/lyubo/react-native-sodium

@geastwood please mention if you have any other library in mind that can be a better replacement.

#### 2. Opening a webview on transactions and load beacon sdk there
one decision here would be:
- If we want to serve it on a server and point the webview to the url
- We want to try to open a local file on the webview ( could be also tricky )

**Comment by geastwood** [comment]
@ahoseinian Thanks for the good wrap up.

However as of native node `crypto`, we do actually run `nodify` to patch the `crypto` implementation, which shouldn't be a probelm.

**Comment by ahoseinian** [comment]
@geastwood The other idea was to replace the libsodium library with a pure javascript cryptography solution. 
here are the list of libsodium methods used by beacon-sdk:

- crypto_sign_ed25519_sk_to_curve25519
- crypto_sign_ed25519_pk_to_curve25519
- crypto_kx_server_session_keys
- crypto_generichash
- from_string
- crypto_sign_detached
- crypto_sign_seed_keypair
- randombytes_buf
- crypto_secretbox_easy
- crypto_secretbox_open_easy
- crypto_box_seal
- crypto_box_seal_open

List of properties
- crypto_secretbox_NONCEBYTES
- crypto_secretbox_MACBYTES

**Comment by ahoseinian** [comment]
@geastwood seems by adding `path` (crypto was already added) module to nodiefy the problem with module import goes away. however, the sdk fails now when trying to use `document.` on global context.
[disabling ui elements](https://docs.walletbeacon.io/advanced/ui-elements) didn't help.

**Comment by geastwood** [comment]
There are quite some methods being used here. It's more complex than I thought. 

In [react-native-sodium](https://github.com/lyubo/react-native-sodium) can we map these calls nicely?

**Comment by geastwood** [comment]
> @geastwood seems by adding `path` (crypto was already added) module to nodiefy the problem with module import goes away. however, the sdk fails now when trying to use `document.` on global context.
> [disabling ui elements](https://docs.walletbeacon.io/advanced/ui-elements) didn't help.

Can we pinpoint where are they referencing `document` directly?

**Comment by geastwood** [comment]
@ahoseinian what about using [this](https://github.com/inokawa/react-native-react-bridge) to wrap everything in a webview. And for now we can even use their UI.

**Comment by ahoseinian** [comment]
About react-bridge: the documentation implementation works well however when importing the beacon sdk I get the following error:

```
[Error: TransformError src/webview/beacon_sdk/BeaconSdkWebView.tsx: Unable to resolve module ./Libraries/Components/AccessibilityInfo/AccessibilityInfo from /Users/amir/projects/litentry/litentry-app/node_modules/react-native/index.js: 

None of these files exist:
  * node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo(.native|.rnrb.js|.native.js|.js|.rnrb.ts|.native.ts|.ts|.rnrb.jsx|.native.jsx|.jsx|.rnrb.tsx|.native.tsx|.tsx|.rnrb.mjs|.native.mjs|.mjs|.rnrb.cjs|.native.cjs|.cjs|.rnrb.htm|.native.htm|.htm|.rnrb.html|.native.html|.html|.rnrb.css|.native.css|.css|.rnrb.bmp|.native.bmp|.bmp|.rnrb.gif|.native.gif|.gif|.rnrb.png|.native.png|.png|.rnrb.jpg|.native.jpg|.jpg|.rnrb.jpeg|.native.jpeg|.jpeg|.rnrb.webp|.native.webp|.webp|.rnrb.svg|.native.svg|.svg|.rnrb.txt|.native.txt|.txt|.rnrb.md|.native.md|.md|.rnrb.wasm|.native.wasm|.wasm)
  * node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo/index(.native|.rnrb.js|.native.js|.js|.rnrb.ts|.native.ts|.ts|.rnrb.jsx|.native.jsx|.jsx|.rnrb.tsx|.native.tsx|.tsx|.rnrb.mjs|.native.mjs|.mjs|.rnrb.cjs|.native.cjs|.cjs|.rnrb.htm|.native.htm|.htm|.rnrb.html|.native.html|.html|.rnrb.css|.native.css|.css|.rnrb.bmp|.native.bmp|.bmp|.rnrb.gif|.native.gif|.gif|.rnrb.png|.native.png|.png|.rnrb.jpg|.native.jpg|.jpg|.rnrb.jpeg|.native.jpeg|.jpeg|.rnrb.webp|.native.webp|.webp|.rnrb.svg|.native.svg|.svg|.rnrb.txt|.native.txt|.txt|.rnrb.md|.native.md|.md|.rnrb.wasm|.native.wasm|.wasm)
  12 |
  13 | // Components
> 14 | import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
     |                                       ^
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
  17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';]
```
so far, I couldn't understand where is this coming from
commit 244d31cc069e57eb150978450f058f62fd48cab7

**Comment by ahoseinian** [comment]
maybe we can build it separatly outside of metro & react native and communicate with it through [`onMessage` on webview](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#the-windowreactnativewebviewpostmessage-method-and-onmessage-prop)

**Comment by geastwood** [comment]
> About react-bridge: the documentation implementation works well however when importing the beacon sdk I get the following error:
> 
> ```
> [Error: TransformError src/webview/beacon_sdk/BeaconSdkWebView.tsx: Unable to resolve module ./Libraries/Components/AccessibilityInfo/AccessibilityInfo from /Users/amir/projects/litentry/litentry-app/node_modules/react-native/index.js: 
> 
> None of these files exist:
>   * node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo(.native|.rnrb.js|.native.js|.js|.rnrb.ts|.native.ts|.ts|.rnrb.jsx|.native.jsx|.jsx|.rnrb.tsx|.native.tsx|.tsx|.rnrb.mjs|.native.mjs|.mjs|.rnrb.cjs|.native.cjs|.cjs|.rnrb.htm|.native.htm|.htm|.rnrb.html|.native.html|.html|.rnrb.css|.native.css|.css|.rnrb.bmp|.native.bmp|.bmp|.rnrb.gif|.native.gif|.gif|.rnrb.png|.native.png|.png|.rnrb.jpg|.native.jpg|.jpg|.rnrb.jpeg|.native.jpeg|.jpeg|.rnrb.webp|.native.webp|.webp|.rnrb.svg|.native.svg|.svg|.rnrb.txt|.native.txt|.txt|.rnrb.md|.native.md|.md|.rnrb.wasm|.native.wasm|.wasm)
>   * node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo/index(.native|.rnrb.js|.native.js|.js|.rnrb.ts|.native.ts|.ts|.rnrb.jsx|.native.jsx|.jsx|.rnrb.tsx|.native.tsx|.tsx|.rnrb.mjs|.native.mjs|.mjs|.rnrb.cjs|.native.cjs|.cjs|.rnrb.htm|.native.htm|.htm|.rnrb.html|.native.html|.html|.rnrb.css|.native.css|.css|.rnrb.bmp|.native.bmp|.bmp|.rnrb.gif|.native.gif|.gif|.rnrb.png|.native.png|.png|.rnrb.jpg|.native.jpg|.jpg|.rnrb.jpeg|.native.jpeg|.jpeg|.rnrb.webp|.native.webp|.webp|.rnrb.svg|.native.svg|.svg|.rnrb.txt|.native.txt|.txt|.rnrb.md|.native.md|.md|.rnrb.wasm|.native.wasm|.wasm)
>   12 |
>   13 | // Components
> > 14 | import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
>      |                                       ^
>   15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
>   16 | import typeof Button from './Libraries/Components/Button';
>   17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';]
> ```
> 
> so far, I couldn't understand where is this coming from
> commit [244d31c](https://github.com/litentry/litentry-app/commit/244d31cc069e57eb150978450f058f62fd48cab7)

It doesn't seem be compiled at all.

**Comment by ahoseinian** [comment]
@geastwood it was not possible to import any resources in html file when statically putting it through webview. however using [inlineChunkHtmlPlugin](https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-dev-utils/InlineChunkHtmlPlugin.js#L10). it was possible to put all the javascript in the html file.

it seems to be loading the SDK for the first step.
<img src=https://user-images.githubusercontent.com/1168983/126616762-c54f0790-2f7d-476b-bd9f-3b9c9fe21b4e.png width=150 />

**Comment by ahoseinian** [comment]
# Results

After implementing the beacon-sdk using an inline html loaded by webview approach, we were able to connect to the sdk and request permissions from different wallets:

kukai wallet demonstrates the process here completely, however this is not a substrate based wallet so we would not be able to use it. 

https://user-images.githubusercontent.com/1168983/126785639-e57ce71d-3efa-4989-bbd2-d6e11b53e2c4.MP4

air-gap wallet supports the polkadot & kusama networks but at the moment there is an issue regarding my account not being found 

https://user-images.githubusercontent.com/1168983/126785762-ccc9ec15-f87a-41f8-a5b1-a1f8682b610f.MP4

and finally the ability to scan any supported wallet in another device is also available.

https://user-images.githubusercontent.com/1168983/126785815-1139b549-0f46-4369-a112-55aeaaa02f23.MP4
