### ISSUE TITLE
Research on WalletConnect

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#193]
Have an overview of WalletConnect with their support on Substrate based network.

Directions: 

* [x] reach out to network, especially wallet provider on the implementation progress and support levels @geastwood 
* [x] check out their website on the completeness of documentation for substrate based network @franjs & @stephanie-olp 
* [ ] Possibly organise meetings with WalletConnect team and other parties who have experiences using it.

**Comment by geastwood** [comment]
@franjs Let's log some of the findings here.

**Comment by geastwood** [comment]
https://docs.walletconnect.org/v/2.0/json-rpc/polkadot
It seems they are still working on this, however it has been like this for the past 6 month.

**Comment by silva-fj** [comment]
After playing with the [examples](https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/examples), The client library seems to be stable enough to integrate it (despite being marked as experimental).

**Comment by silva-fj** [comment]
As we can see [here](https://twitter.com/WalletConnect/status/1402611222873313283?s=20). They said that it is ready for production (the js client) but apps need to wait for wallets to support v2.0. 

I also did some research on the status of some of the most known [supported wallets](https://registry.walletconnect.org/wallets) and currently there is still no support for v2.0 (I could not find any progress or roadmap for adding support for it)

**Comment by geastwood** [comment]
> As we can see [here](https://twitter.com/WalletConnect/status/1402611222873313283?s=20). They said that it is ready for production (the js client) but apps need to wait for wallets to support v2.0.
> 
> I also did some research on the status of some of the most known [supported wallets](https://registry.walletconnect.org/wallets) and currently there is still no support for v2.0 (I could not find any progress or roadmap for adding support for it)

Yeh, that's a bummer! Let me ask around see if there is any wallets already started testing it.

**Comment by geastwood** [comment]
However I think they must have a way of testing this while developing it, no?

**Comment by silva-fj** [comment]
The example wallet is using [this](https://github.com/pedrouid/caip-wallet/tree/beta) internally, but it does not have support for polkadot yet, they started to implement cosmos first. We could make it to work, but we would have to implement the polkadot signer and change a few things in the examples (I was playing with the code and does not seem to be much work if the wallet is ready).. However how to integrate the substrate jsonrpc provider and the methods is not very clear, we would need to play a bit with it as well and update the examples accordingly

**Comment by geastwood** [comment]
Asked MathWallet and PolkaWallet, both haven't started integrating the WalletConnect 2.0. It seems we are the first.

**Comment by silva-fj** [comment]
In the current state of WalletConnect 2.0 we can integrate the client in our app, however there is currently no way to test it without adding polkadot support to the wallet example provided in the examples and extend it to make something more than just creating a session between the app and the wallet.
 
Basically to make the examples to work we need to add a polkadot signer and jsonRpc provider implementations on the [caip-wallet](https://github.com/pedrouid/caip-wallet/tree/beta)

Ideally we should wait for one of the well known wallets to migrate to WalletConnect 2.0 or until the examples are updated as well as the docs:
- https://docs.walletconnect.org/v/2.0/json-rpc/polkadot
- https://docs.walletconnect.org/v/2.0/quick-start/dapps/web3-provider

**Comment by geastwood** [comment]
A follow up question. In `capi-wallet` repo, if we were to extend the functionality to polkadot, or in general substrate-based network. How could we easily test the signer completeness within that repo, I guess for other signers they have some basic unit tests for that yeh?

**Comment by silva-fj** [comment]
The signers are classes that must implement an interface that defines all methods needed, so in terms of completeness we would be covered by typescript. But they also have some unit tests as well
