### ISSUE TITLE
Research `substrate-api-sidecar`

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#244]
Repo:
https://github.com/paritytech/substrate-api-sidecar

Check how this can help getting data for native and web app.

Let's document some of the findings here.

**Comment by ahoseinian** [comment]
@geastwood  I've made [a small summary of sidecar on notion](https://www.notion.so/litentry/ParityTech-Substrate-api-sidecar-bca1664eeb854507818df33e5cf43227). we can link this to the main study about indexer and other solutions when we have the notion page.
