### ISSUE TITLE
Feature: Governance Actions | Submit a preimage

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#266]
> As a Dot holder, i wanna submit a preimage so I can submit a proposal

At some point before the proposal passes you will need to submit the preimage or else the proposal cannot be enacted.

When the users clicks on "Submit a preimage" from the democracy screen the following form should open
<img src="https://user-images.githubusercontent.com/85941267/128844577-f6068e3b-d21c-4893-b2bc-e755affc4407.png" width="275" height="560">
This form changes according to which purpose has been selected by the user from the dropdown list. 
Nevertheless the following sections are not affected by that selection:
* Send from account
* Preimage hash
* Calculated storage fee (⚠︎ The unit changes though)

The propose section evolves according to the propose chosen by the user. 26 scenarios exist: 
* Scenario 1 : Propose = authorship
<img src="https://user-images.githubusercontent.com/85941267/128865208-2e9d9339-ba5f-432e-a3f5-0fe3e972b995.png" width="275" height="560">

* Scenario 2: Propose = babe

* Scenario 3: Propose = balances

* Scenario 4: Propose = bounties

* Scenario 5: Propose = claims

* Scenario 6: Propose = council

* Scenario 7: Propose = democracy

* Scenario 8: Propose = electionProviderMutiphase

* Scenario 9: Propose = grandpa

* Scenario 10: Propose = identity

* Scenario 11: Propose = imOnline

* Scenario 12: Propose = indices 

* Scenario 13: Propose = multisig

* Scenario 14: Propose = phragmenElection

* Scenario 15: Propose = proxy

* Scenario 16: Propose = scheduler

* Scenario 17: Propose = session

* Scenario 18: Propose = staking

* Scenario 19: Propose = system

* Scenario 20: Propose = technicalCommittee

* Scenario 21: Propose = technicalMembership

* Scenario 22: Propose = timestamp

* Scenario 23: Propose = tips

* Scenario 24: Propose = treasury 

* Scenario 25: Propose = utility

* Scenario 26: Propose = vesting

**Comment by ahoseinian** [comment]
<img width=450 src="https://user-images.githubusercontent.com/1168983/129019424-ebb9c835-d67d-4ff7-b889-6d7b68b97f51.png" align="right" />Preimage `propose` field is consisted of three different parts:

## Section & Method
These parts are extractable from api and should be simple enough to implement. All these can be found in `apiPromise` object. we would have a list of all sections and populate the list of methods according to the selected section. 

##  Params
While it is simple enough to implement components for selection a `section` & `method`, each combination of the two would have different params associated with them. These params would have different types which is mapped to 27 different components in this [Mapping](https://github.com/polkadot-js/apps/blob/d744e6bbea326219f2060665d858540ef8a23b53/packages/react-params/src/Param/findComponent.ts#L47). This makes things much more complicated!


### What can be done?
Attempting to implement all of these (especially the params) in one ticket does not seem advisable. moreover, we would need to figure out how much business value does this part has and does it worth spending probably couple of weeks implementing all of these logic.

If we decide this is a important enough part of governance app function and we would not be able to do without it. my suggestion is to break this ticket into multiple parts. for example implementing all the simple param types first and more complicated onces in different tickets.

---
<img align="right" width="300" src="https://user-images.githubusercontent.com/1168983/129021792-b832c66e-0624-4650-866e-29a7d88abee5.png" />
One more interesting point that makes matter more complicated is that a `Call` parameter can refer to another `Call` parameter and make a loop of params:

**Comment by ahoseinian** [comment]
@geastwood @stephanie-olp @franjs ⬆️ ⬆️

**Comment by stephanie-olp** [comment]
Hey guys, 
Ben and Tim also looked at preimage. As preimage form is dynamic and it would take a very long time to map out all the possibilities they recommend us to take a look at the below links and use code to dynamically create the preimage inputs based on user selection. (Rather than trying to manually map out the possibilities).
* https://wiki.polkadot.network/docs/maintain-guides-democracy#submitting-a-preimage
* https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/Extrinsic.tsx
* This is the file where it figures out the input component: https://github.com/polkadot-js/apps/blob/master/packages/react-params/src/Param/index.tsx

If you have any questions, Ben said he will happily answer to it

**Comment by ahoseinian** [comment]
Hey @stephanie-olp & @bdmason ,

Yes this is the same `Mapping` I referred to in my comment. unlike the web project we can't use this because it's not written with react-native in mind. all the components are using react/html elements which would not work in our environment.
