### ISSUE TITLE
Research: As a user I'd like to have to discuss with other members of the community 

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#270]
As a user I'd like to have discussion with other members of the community

This is also part of Milestone 3 "Allow users to participate in discussions from Polkassembly natively in app"

- [x] How to enable users to participate in discussion from [Polkassembly ](https://polkadot.polkassembly.io/discussions) within our App  ? How complex is it and how much time is it gonna take ? 

- [x] Do we want just want to show the discussion that are Polkassembly on or is there another way to do it (other type of discussion within the community)  ? 

- [ ] What about [Polkaverse](https://polkaverse.com/?tab=posts&type=suggested&date=day) ?

**Comment by ahoseinian** [comment]
### Polkassembly 
The api is accessible through a graphql endpoint on https://polkadot.polkassembly.io/v1/graphql.
Using the endpoint we can read posts and even login and write posts or comments if necessary.

### Other discussion places
- Element: Polkadot watercooler https://riot.im/app/#/room/!FdCojkeGzZLSEoiecf:web3.foundation
- Reddit: https://www.reddit.com/r/Polkadot/ & https://www.reddit.com/r/dot/

### Polkaverse & subsocial
I could not find any info on how to use subsocial apis to show their data on the app. if necessary, maybe going through their code on https://github.com/dappforce/subsocial-web-app can help to get a better understanding.

**Comment by silva-fj** [comment]
The docs of the javascript SDK of subsocial could also help us to better understand how to interact with the api 
https://docs.subsocial.network/js-docs/js-sdk/index.html
