### ISSUE TITLE
Update react-navigation to V6

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#275]
React navigation 6 has been released. There are some breaking changes and as well as some deprecations that need to be addressed.

More info:
https://reactnavigation.org/blog/2021/08/14/react-navigation-6.0
https://reactnavigation.org/docs/upgrading-from-5.x

**Comment by geastwood** [comment]
How complex is it to migrate?

**Comment by silva-fj** [comment]
> How complex is it to migrate?

It should be easy, the api has not changed much. Just some config needs to be modified and adjust the types
