### ISSUE TITLE
Research: Polkascan explorer

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#290]
- [x] Look at Polkascan API (complexity, cost, process)
I also remember Francisco mentioning something about chain and off-chain data. 

- [ ] How would the UI/UX look like ?

**Comment by ahoseinian** [comment]
- [X] Look at Polkascan API (complexity, cost, process)
### Polkascan open source
There is a open source version available of the polkascan website. These provide services for [harvesting](https://github.com/polkascan/polkascan-pre-harvester) data from the chain, and a [REST api](https://github.com/polkascan/polkascan-pre-explorer-api). These would help us to harvest the same data for litentry chain as well. and also, we would be able to host the harvester and api ourselves.


However, I wasn't able to get [polkascan-os](https://github.com/polkascan/polkascan-os) to work on my local machine. there were problems on docker compose that I couldn't fix. 

 but also we can just simply use polkascan public api like https://explorer-32.polkascan.io/api/v1/kusama/networkstats/latest to get the data from their hosted version of harvested data for Kusama and Polkadot chains.

**Comment by geastwood** [comment]
Yeh, we actually have close contact with this project, and it's one of few substrate based blockchain explorer. However I don't think they are still active on the development, which partially explains the docker issue you have experienced.
