### ISSUE TITLE
Polish Identity 

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#296]
I understood that we wanted to work on some glitches and missing features/actions related to identity on the app 
but I'm not sure what has to be done there. @franjs @geastwood @ahoseinian  do you think you can complete this list? :

- [x] #303
- [x] #320
- [x] #322
- [x] #327
- [x] #331

**Comment by silva-fj** [comment]
### This is what we currently have for Identity

**Set Identity** 

https://user-images.githubusercontent.com/8374946/130641681-3ced77d0-95af-467e-af58-76bdc40ead86.mov

**Clear Identity**

https://user-images.githubusercontent.com/8374946/130641776-bb3bbb97-75ba-4e06-8bad-4eff85f6e0d9.mp4

**Request Judement**

https://user-images.githubusercontent.com/8374946/130642028-209ec291-182e-4351-a32b-839e408fdec8.mp4

https://user-images.githubusercontent.com/8374946/130642051-8b2b73d8-62b9-4aaa-8979-5a81e8c38bea.mp4

https://user-images.githubusercontent.com/8374946/130642097-d26d9a33-1d4a-4f55-8db3-0e5fb028c631.mp4

**Comment by silva-fj** [comment]
As you can see on the videos, there is a bug on the multi-account view (the account teasers does not get updated when the account's status has changed). The transactions take some time, we need to check if we can do something about it (like providing more feedback to the user or to have some kind of pending status and display a toast message once the transaction has resolved) or just check if there is an issue in our code (on the polkadotjs app does not seem to take that long)
