### ISSUE TITLE
Feature: List of discussions on Polkassembly

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#304]
> As user I'd like to see the different discussions occurring on Polkadot within the app.

For both iOS and Android users

### ⚠️ what do we need?

- [x] UI/UX : Where is the entry point ? A teaser on the dashboard or just in the drawer ?  
- [ ] Should we have this feature it in Litentry Testnet or only in the Kusama and Polkadot network ? (ask @geastwood )
- [x] Add filters to the discussion list: What are the filters

**Comment by stephanie-olp** [comment]
**UI/UX :**
For now let's just have an entry point in the drawer, I'll have a discussion with Jutta about a potential teaser on the dashboard.

**Comment by stephanie-olp** [comment]
- **Filters**
On Polkaseembly the user can filter the list of discussion per "Last commented" , "Newest" and "Oldest"

Also I saw that the different discussion are labeled by category : "Democracy", "Treasury" , "Tech Committee" and "General" . What do you think about using those as filters ? 

- **UI/UX** 
I've talked with Jutta and she will take integrate a "Latest Discussions" teaser on the Dashboard. 
So we will have 2 entry points: the drawer (in this ticket) and the dashboard (to be done later)
<img src="https://user-images.githubusercontent.com/85941267/130475612-f539e4cb-8dca-4d9f-a13e-8fb7490f1b10.png" width="240" height="500"> <img src="https://user-images.githubusercontent.com/85941267/130475733-4e5f2399-c04c-4fbe-86e0-3fa1763ce060.png" width="240" height="500">

**Comment by ahoseinian** [comment]
https://user-images.githubusercontent.com/1168983/130826916-5f33dcb7-54d4-4456-b390-7b6b6368ead6.mp4

**Comment by stephanie-olp** [comment]
Awesome ! Everything looks great
