### ISSUE TITLE
Set identity Guide

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#327]
> As a user 'd like to understand the steps to set an identity

As the steps of setting an identity can be confusing, it would be nice to show the user a step by step guide before the actual process of setting an identity. So before showing him this screen: 
![image](https://user-images.githubusercontent.com/85941267/130799805-0db76226-dbd2-42e8-beb3-1b0c0b37978a.png)

He should see the following screens:

**The user should be able to skip this guide at any steps**

<img src="https://user-images.githubusercontent.com/85941267/130923388-880f9d99-3b76-448f-b8bf-af7833f8aab6.png" width="275" height="600">   <img src="https://user-images.githubusercontent.com/85941267/130800361-ab41bf90-b3d1-4d67-81b5-b859a72c2971.png" width="275" height="600"> <img src="https://user-images.githubusercontent.com/85941267/130923664-1c7b7cd3-e8c5-4df2-aec6-a5e1c0918367.png" width="275" height="600">

Here are the pictures I used for the mockups:
[Steps .pdf](https://github.com/litentry/litentry-app/files/7047429/Steps.pdf)

**Comment by ahoseinian** [comment]
@stephanie-olp should we show it only once or every time user opens set identity?

**Comment by stephanie-olp** [comment]
@ahoseinian As the user can skip the tutorial, I think it's okay if we show it every time he clicks on the CTA "Set identity"
