### ISSUE TITLE
Bug: What happens when last step of "set identity" fail ?

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#331]
> As a user I'd like to understand why the submission of my identity doesn't work

After I've been through all different steps of "set identity", the app is stuck on this screen (waited for more than 5 minutes nothing happens) :
<img src="https://user-images.githubusercontent.com/85941267/131115459-a38efd26-5791-410d-b8b3-1e6d77df9964.png" width="275" height="600"> 

Finally I just touched another area of the screen which closes the and I end up on that screen where I have to begin the whole process again:
<img src="https://user-images.githubusercontent.com/85941267/131115476-a0b7f690-3e92-448c-885f-6e2d09e6473d.png" width="275" height="600"> 

We have to understand what's happening there ? If it's a problem with the submission we should display an error message to the user so he doesn't wait hoping for something to happen. It's even better if we can tell the user what went wrong with the submission

**Comment by geastwood** [comment]
We have to have a timeout here like if the tx is more than 2 minutes, there must be some issues.

Which reminds me another thing is how we check the success of a tx, can we double check on the way we handle chain response after a tx is broadcasted? It seems we have to wait for quite sometime for a tx.
