### ISSUE TITLE
Bug: Account Teaser not displaying sub accounts correctly

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#334]
Sub accounts should display the parent account name as well as the sub-identity name as shown here: 

<img width="447" alt="Screenshot 2021-08-30 at 9 42 58 AM" src="https://user-images.githubusercontent.com/8374946/131304408-a83ac720-a53c-4eed-8442-1b50c3c8bef1.png">

Currently the teaser is only displaying the parent account name:

<img width="417" alt="Screenshot 2021-08-30 at 9 41 03 AM" src="https://user-images.githubusercontent.com/8374946/131304500-40a79b82-0d4b-4096-aec9-95ac03ee65b1.png">

This is a regression bug, it was introduced in this [PR](https://github.com/litentry/litentry-app/pull/237)

This is what the old hook (`useAccountDetail`) was returning:

```
const displayFull = subAccountDisplay ? `${display}/${subAccountDisplay}` : display;
```

**Comment by geastwood** [comment]
@ahoseinian can you please take a look, and revert some of the code in the old hook.

**Comment by ahoseinian** [comment]
@geastwood will do 👍
