### ISSUE TITLE
Add Action "Create a new Bounty"

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#370]
As a dot holder, I'd like to add a bounty.

* On the bounty list add a "Add a bounty" button:

<img src="https://user-images.githubusercontent.com/85941267/134487591-af31df79-cd2c-4229-a024-54dd7bfdc949.png" width="275" height="580">
* When user clicks he should see the following: 

<img src="https://user-images.githubusercontent.com/85941267/134488216-cc546924-e924-4336-a5a8-75ee7bf50e6f.png" width="275" height="580">

**Comment by stephanie-olp** [comment]
Sorry wrong colors : Proposed = yellow, Claimed = green, Rejected = red

**Comment by stephanie-olp** [comment]
![image](https://user-images.githubusercontent.com/85941267/134641747-ea4225ab-a8f1-45c1-936b-28f9625714d2.png)

**Comment by geastwood** [comment]
Is it correct to close this? It's closed by stale bot.
