### ISSUE TITLE
Technical Committee Screen 

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#371]
> As a user I'd like to know who compose the Technical Committee

* Technical Committee screen should be accessible from a navigation point in the drawer

<img src="https://user-images.githubusercontent.com/85941267/134647280-f8501d8b-17fe-477f-ad92-582e8f6e39e6.png" width="275" height="570">

**Comment by geastwood** [comment]
Should this be reopened? Or it becomes irrelevant? @stephanie-olp
