### ISSUE TITLE
multi account view

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#38]
* [ ] dedicated view on accounts
* [x] able to remove accounts

* accounts are aggregated, e.g. polkadot accounts are listed together with kusama account
* To be scoped

**Comment by geastwood** [comment]
duplicate with #65

**Comment by stephanie-olp** [comment]
User Flow:
![image](https://user-images.githubusercontent.com/85941267/124259720-207de700-db2f-11eb-8c7f-233d5e81505a.png)

**Comment by stephanie-olp** [comment]
New UX version more practical when user has lots of accounts:
![image](https://user-images.githubusercontent.com/85941267/124483528-bc675700-ddaa-11eb-9386-057c7d8c1614.png)

**Comment by stephanie-olp** [comment]
For now the user can't do any actions on the Council and Treasury screens. So the only screens we have to modify is the Submit Tip Screen
![image](https://user-images.githubusercontent.com/85941267/124568694-7b705080-de45-11eb-8cce-139e5cd00847.png)

For the referenda screen, we already added a place to pick the right account
