### ISSUE TITLE
Remove previous accounts section

### ISSUE THREAD

**Issue by ahoseinian** [litentry/litentry-app#393]
- Add set sub-identities & clear Identity button to Manage Identity Page
- Remove the previous accounts section from drawer

![Screenshot 2021-09-22 at 11 31 35](https://user-images.githubusercontent.com/1168983/134319778-b3dd085b-7fba-4153-a526-b7dff55280ec.png)

> How do we clear identities and set sub identities now?

_Originally posted by @franjs in https://github.com/litentry/litentry-app/pull/386#pullrequestreview-760591818_

**Comment by stephanie-olp** [comment]
Successfully tested on iOS
