### ISSUE TITLE
Provide details when setIdentity

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#40]
Provide information like how many token will be reserved, what's the next step, etc.

The app should provide user more info on what happens when `setIdentity` is called. 

1. it will reserve some native token of the network (exactly how many depends on the setting)
2. Only after user called `setIdentity`, they can `requestJudgement`

### Design challenge
* find a good ui/ux to add such info
* info should strive to be clear and concise

**Comment by ahoseinian** [comment]
@geastwood could you please more info here?

**Comment by geastwood** [comment]
I have update the description. If there is still anything unclear. Let's log them in discussion.
