### ISSUE TITLE
Crowdloan item details screen

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#412]
> As a user I want more details on a particular Fund

When the user clicks on one of the fund in the Crowdloan list it should open a screen with the following information:
- Name of the project
- Index 
- Depositor
- Ending
- Leases
- Raised amount
- Count
- Status
- A link to be redirected to that project webpage

Wireframe:
![image](https://user-images.githubusercontent.com/85941267/135817266-76d49f9e-5534-45cb-9bc1-506c89103a0b.png)

**Comment by ahoseinian** [comment]
duplicate #439
