### ISSUE TITLE
Research technical challenges with a focus on security.

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#417]
See how other apps are doing:
- Parity Signer (ask @hanwencheng)
- PolkaWallet

**Comment by geastwood** [comment]
* Parity signer
* PolkaWallet

**Comment by silva-fj** [comment]
Polkawallet encrypts the seeds and stores them using https://pub.dev/packages/shared_preferences. ([code reference](https://github.com/polkawallet-io/sdk/blob/7df91bb02441ef89f8a8c87d474ee296458f5537/lib/storage/keyring.dart#L246))

and https://pub.dev/packages/get_storage to store the key pairs locally. ([code reference](https://github.com/polkawallet-io/sdk/blob/7df91bb02441ef89f8a8c87d474ee296458f5537/lib/storage/localStorage.dart))

They use a wrapper of polkadot's Keyring to manage the key pairs ([code reference](https://github.com/polkawallet-io/sdk/blob/7df91bb02441ef89f8a8c87d474ee296458f5537/lib/storage/keyring.dart))

We can use https://github.com/oblador/react-native-keychain to store sensitive info in the devices (making use of [Keychain](https://developer.apple.com/documentation/security/keychain_services) and [Keystore](https://developer.android.com/training/articles/keystore) for IOS and Android respectively) in combination with https://github.com/mrousavy/react-native-mmkv which also has encryption support and is much faster than AsyncStorage

**Comment by silva-fj** [comment]
Another reference is the [stylo app](https://github.com/stylo-app/stylo) (a fork of the Parity Signer) built with react native.

**Comment by geastwood** [comment]
* `shared preference` seems to be a bit off, at least not sufficient. @franjs what do you think?

* I guess for substrate based network we have to somehow make our implementation based on `keyring`. However, it's still a good idea to wrap it, leave us more freedom in the future to integrate other networks.

The thing I don't really like `keychain` (specific to iOS), it syncs with iCloud, that's kinda of implicit knowledge, not something immediately become clear when a user creates a wallet.

**Comment by geastwood** [comment]
Plus, I want to emphasize in case it's not known by everyone, users still have to choose a password, or a passphrase, which we use to encrypt and save the encrypted text to the device.

**Comment by silva-fj** [comment]
> shared preference seems to be a bit off, at least not sufficient. @franjs what do you think?

Agree. Even though they are encrypting the data, using a secure storage adds another layer of security which is better.. The more layers we put, the more difficult it will be for an attacker to get the data.

> I guess for substrate based network we have to somehow make our implementation based on keyring. However, it's still a good idea to wrap it, leave us more freedom in the future to integrate other networks.

Yeah it's a good idea to encapsulate that, so we can easily add other implementations for other networks

> The thing I don't really like keychain (specific to iOS), it syncs with iCloud, that's kinda of implicit knowledge, not something immediately become clear when a user creates a wallet.

That's actually a good concern, I wonder if it's possible to disable it

**Comment by silva-fj** [comment]
The MetaMask mobile app is also built with react native. It's also another good [reference](https://github.com/MetaMask/metamask-mobile)

**Comment by franjs** [comment]
I have not used [Realm](https://docs.mongodb.com/realm/sdk/react-native/) but it may be worth to take a look since the database can be encrypted. https://docs.mongodb.com/realm/sdk/react-native/advanced/encrypt/

**Comment by geastwood** [comment]
@ahoseinian @ishrak-imam also get some exposure to another project like metamask.
