### ISSUE TITLE
Get to know the basic of Custodial wallet

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#420]
- [x] Everyone should read a bit about the Non Custodial wallet:
Technical doc on BIP39: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
Custodial vs Non-custodial wallet: https://appinventiv.com/blog/custodial-vs-non-custodial-wallets/
Advance material (difficulty increase gradually): https://youtube.com/playlist?list=PLPQwGV1aLnTtAmzmz6uVE0kTKXtaGX1zY
- [ ] Presentation to the rest of the team (much later)

It would be great that some of the learnings can be organized into a presentation to offer others insights.

**Comment by geastwood** [comment]
Technical doc on BIP39: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

**Comment by geastwood** [comment]
Custodial vs Non-custodial wallet: https://appinventiv.com/blog/custodial-vs-non-custodial-wallets/

**Comment by geastwood** [comment]
Advance material (difficulty increase gradually): https://youtube.com/playlist?list=PLPQwGV1aLnTtAmzmz6uVE0kTKXtaGX1zY

**Comment by geastwood** [comment]
@litentry/rn-team

**Comment by silva-fj** [comment]
Basic info about wallets: https://academy.binance.com/en/articles/crypto-wallet-types-explained
