### ISSUE TITLE
Bug: Switching network doesn't invalidates queries properly

### ISSUE THREAD

**Issue by ishrak-imam** [litentry/litentry-app#441]
`queryClient.clear()` in ChainApiContext doesn't seem to be working properly. Some screens displays the previous cache value after network switching. Example `RegistrarScreen`

## Steps To Reproduce

1. Go to registrar screen
2. Go back to dashboard and switch network
3. Go to register screen again

**Comment by stephanie-olp** [comment]
Successfully tested on iOS
