### ISSUE TITLE
Bug: Can't install app on Android with APK after build n°156

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#477]
> Both Rodrigo and me tried to download the latest Bitrise build but once we open the APK file on our phones and tried to install the App from we get the following error message: 

<img src="https://user-images.githubusercontent.com/85941267/136522084-1e4ee790-b385-4af3-9e9f-8f4a69243566.png" width="275" height="600"> 

After some investigations, it seems like this error occurred for **every builds after build n°156** 

App version: After build n°156

## Steps To Reproduce
On your **Android device** : 
1. In the RN app channel on slack find one of the latest Bitrise build and click on install page
2. A Bitrise page should open, there click on download
3. It should download the APK on your device. Go in your downloaded files and open the Apk file you just downloaded
4. A pop up asks you  if you wanna download/ update the app, click on install
5. At the end of the download you should get an error message "App not installed"

**Comment by silva-fj** [comment]
@geastwood can you take a look a this when you have time? I think it's the same issue we had before when signing the app

**Comment by geastwood** [comment]
Ok, will take a look.

**Comment by geastwood** [comment]
Actually didn't find anything specific, @franjs would you create a ticket on Bitrise?
