### ISSUE TITLE
Bug: Performance issues on the Parachain detail screen

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#485]
When loading the screen and scrolling down the list of Non Voters the app freezes a bit.

Also the following warning is displayed in the console:

`VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 9619, "dt": 1116, "prevDt": 1183}
`

**Comment by ishrak-imam** [comment]
Working on this in the following ticket.
https://github.com/litentry/litentry-app/issues/444
