### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#49]
# Governance App Milestone 1

With this document, we intend to communicate with the community about the Governance App development progress (**Milestone 1**, original proposal can be found [here](https://polkadot.polkassembly.io/motion/49)). This document is divided into the following sections to allow reader to quickly navigate:

1. Summary
2. Detail rundowns according to tasks in **milestone1**
3. Next steps
4. Resources

## Summary

Firstly, we are thrilled to announce we have fulfilled all the tasks in **milestone 1** as presented in the original proposal. However, it is not a smooth ride. We have experienced quite some challenges along this way, some of which have caused a delay in delivering this milestone than we expected. We want to highlight the most notable ones here to provide **councillors** and **community members** better context.

The first challenge is that we have underestimated the amount of work to bootstrap a functional app. The tasks listed in **milestone 1** made the assumptions that basic functionalities are already available (functions such as import account, switch network, present account data, etc.). This means in order to have a presentable app, we have to develop additional functionalities as foundational work.

One of the technical challenges is to bring `polkadotjs` into `React Native` environment. Although the process is somewhat time consuming, it's largely manageable. However, upon implementing **Tx signing** via QR code, we have been blocked for approximately a week. And here is the [GitHub issue](https://github.com/polkadot-js/api/issues/2911) for reference. Luckily with the help from the community (especially from [@jacogr](https://github.com/jacogr)), it is solved at the last.

Another challenge worth mentioning is that onboarding another dev to Polkadot/Kusama ecosystem and get up to speed in development is not a trivial matter.

Finally, the Binance listing of Litentry incurred quite some work for the entire team from the end of January to mid of February 2021.

## Detail rundowns on Milestone 1

In this section, each task will be individually presented with either code references or app screenshots with a reasonable description.

**1.1	Design Register Backend (BE) to be able to verify Email, riot, and Twitter data**

- Becoming a registrar and providing a optimised identity related services  has been part of Litentry's mission since the beginning. And we designed the this service to provide automatic verifications for Email, Riot and Twitter (only offer **Reasonable** judgement).
- The Referendum of including this Registrar on Kusama network has passed ([https://kusama.polkassembly.io/referendum/104](https://kusama.polkassembly.io/referendum/104))
- The code is open sourced and hosted [here](https://github.com/litentry/litentry-registrar).
- The referendum includes a detailed description of the implementation.

**1.1	Implement in BE of chain monitoring on identity events**

- This part of the function is currently embedded in the registrar service.
- For more information, please refer the the Registrar repository
- Here is the [code reference](https://github.com/litentry/litentry-registrar/blob/a57ca1f4b5fbac02545c3ee247b9377057809d3a/app/chain/index.js)

**1.2	Implementation of submission of judgment based on the verified result**

- Based on verification result, the registrar service can provide corresponding results
- Here is the [code reference](https://github.com/litentry/litentry-registrar/blob/a57ca1f4b5fbac02545c3ee247b9377057809d3a/app/chain/index.js#L183)

**1.2	Add database layer to BE to persist processed verification**

- We have introduced the `mongodb` to the Registrar service
- With database support we are able to offer better user experiences in the following aspect:
    - Provide user with good feedback on what is the current state of verification
    - Only provide judgement when all identity fields are verified (e.g. Email and twitter are both verified)
- Here is an example of the [code reference](https://github.com/litentry/litentry-registrar/blob/a57ca1f4b5fbac02545c3ee247b9377057809d3a/app/db/index.js#L133)

**1.3	Able to scan address from different source and display its Identity data (e.g. Judgment status)**

|   |   |   |
|---|---|---|
| ![Add Account View](https://user-images.githubusercontent.com/1623359/111382317-20a0c680-86a7-11eb-9ba2-623520882420.png)  | ![Simulator Screen Shot - iPhone 11 - 2021-03-16 at 22 30 47](https://user-images.githubusercontent.com/1623359/111382580-737a7e00-86a7-11eb-92dd-816f313337d8.png)  |![Simulator Screen Shot - iPhone 11 - 2021-03-16 at 22 30 55](https://user-images.githubusercontent.com/1623359/111382585-74abab00-86a7-11eb-8963-dde74c2e0e0a.png)|
|  ![Simulator Screen Shot - iPhone 11 - 2021-03-16 at 22 31 03](https://user-images.githubusercontent.com/1623359/111382583-74abab00-86a7-11eb-906c-232626feddc2.png) | ![Simulator Screen Shot - iPhone 11 - 2021-03-16 at 22 31 11](https://user-images.githubusercontent.com/1623359/111382581-74131480-86a7-11eb-8ded-8db479a6b357.png)  |  
> Note: The QR code import process works the same.

**1.3	Support signing Tx with QR code (integration with Parity Signer and other offline wallets)**

|   |   |   |
|---|---|---|
|![Signing with QR code](https://user-images.githubusercontent.com/1623359/111493772-2ac1d400-873e-11eb-9c74-ff177a3dfe10.png) | ![Tx success](https://user-images.githubusercontent.com/1623359/111493839-39a88680-873e-11eb-9659-42a3c3e8f01c.jpg) | ![Submitting Tx](https://user-images.githubusercontent.com/1623359/111493841-3a411d00-873e-11eb-9632-330cd8a4e9de.jpg)|

**1.4	Design UI/UX to allow user submit identity Info (via forms)**

![Display of account without identity](https://user-images.githubusercontent.com/1623359/111493627-0960e800-873e-11eb-9567-e8cb507f193e.png) ![Set Identity form](https://user-images.githubusercontent.com/1623359/111493631-09f97e80-873e-11eb-82ba-9fe54c7f04b1.png)

**1.4	Allow user to request judgment and display its status**

|   |   |
|---|---|
| ![Set Identity](https://user-images.githubusercontent.com/1623359/111495495-b7b95d00-873f-11eb-86b6-a220ce44d29b.jpg)|![My Identity View](https://user-images.githubusercontent.com/1623359/111495088-52fe0280-873f-11eb-8201-75d22d8efa47.png) | 

**Other features (Not defined in tasks of Milestone 1)**

| Balance Display  | Drawer View  | Network selection  |
|---|---|---|
| ![Balance display view](https://user-images.githubusercontent.com/1623359/111385084-8fcbea00-86aa-11eb-8d4b-e21fdd792139.png)   |  ![Drawer view](https://user-images.githubusercontent.com/1623359/111385347-f2bd8100-86aa-11eb-9fd2-b89d5a28d96b.png) | ![Network selection](https://user-images.githubusercontent.com/1623359/111385394-049f2400-86ab-11eb-940b-c92600d3e4aa.png)  |

|  **Tips views** |   |   |
|---|---|---|
|  ![Dashboard view 1 (with Tips section)](https://user-images.githubusercontent.com/1623359/111385564-49c35600-86ab-11eb-982e-5d61173d914a.png)| ![Tips list view](https://user-images.githubusercontent.com/1623359/111385563-492abf80-86ab-11eb-8098-b4fa048dd7ac.png)  | ![Tip detail view](https://user-images.githubusercontent.com/1623359/111385557-48922900-86ab-11eb-8b0f-6d3fb9f40dd7.png)  |

- Already start testing on Push Notifications, which is part of *Milestone 2*, the repository can be found [here](https://github.com/litentry/push-notification).
- Support account input with both manual input and QR code scanning
- Able to display user's balance in App
- Able to display a view of available registrar services of either *Polkadot* or *Kusama*

## Next steps

- support more Tx, such as **Voting** related extrinsics
- Allow internal testing via *TestFlight* and *Play store* internal channel
- Modify some tasks in milestone 2 based on the insights gathered and submit milestone 2

## Resources

1. [Motion #49](https://polkadot.polkassembly.io/motion/49)
2. [GitHub: Governance App](https://github.com/litentry/litentry-app)
3. [GitHub: Push notification repo](https://github.com/litentry/push-notification)
4. [GitHub: Registrar](https://github.com/litentry/litentry-registrar)
5. [Referendum of becoming a Kusama registrar](https://kusama.polkassembly.io/referendum/104)

**Comment by geastwood** [comment]
Testing Report:

https://hackmd.io/@rrk/Syjie6Y4u

**Comment by ahoseinian** [comment]
moved to wiki https://github.com/litentry/litentry-app/wiki/Milestone-1
