### ISSUE TITLE
Feature: Store the user's password in the keychain/keystore

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#508]
When creating/importing accounts the user needs to define a password to encrypt the key pair. Then to be able to sign transactions the user needs to unlock the account (introduce the password). We should add the option to the user so they can store the password in the keychain/keystore so they can use biometrics (FaceID / TouchID) to unlock the accounts instead of having to type the password every time they need to make a transaction.

- Use the SecureKeychain service we already have.
- Store the password when creating/importing accounts.
- Retrieve the password from the keychain when signing transactions.

**Comment by ahoseinian** [comment]
current setup for keychain seems to be intended for having only one password saved. with current implementation ( each mnemonic seed has it's own password ) we need to change that a bit.
