### ISSUE TITLE
Bug: Reveal password button not working on iOS

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#516]
In the latest build of iOS

## Steps To Reproduce

1. Go to the account section
2. Click on Import or Create an account
3. Type a password in the **new password for the account** field
4. Try to click on the eye icon next to it

## The current behavior:
Password still hidden

## The expected behavior
The password should be revealed

**Comment by silva-fj** [comment]
@stephanie-olp This is working fine for me, on the Simulator and with the latest build installed in my device. Can you double check that this is still an issue for you?

**Comment by stephanie-olp** [comment]
@franjs I've just tried again when I was testing the new UX flow for creating an account and yes it did work this time but then I tried to import an account and it didn't. More generally the whole section "new password for the account" and "confirm password" lagged so much that I couldn't finish the action.

**Comment by silva-fj** [comment]
I cannot reproduce the issue on my devices or the similator/emulator. Can you make a video with the issue? Maybe there is something i'm missing.

**Comment by stephanie-olp** [comment]
https://user-images.githubusercontent.com/85941267/139038475-045b8923-78e7-4d35-87a4-fbbbf1eef907.mov

I'm not sure the video will be really useful: it's hiding the password during the screen capture.
At the end of the video we can't see it but I filled both "new password" and "confirm password" fields.
I tried then to click on the eye to reveal the password but nothing happens

**Comment by stephanie-olp** [comment]
With the latest improvement, I can't reproduce this issue anymore
