### ISSUE TITLE
Polkadot treasury motion #29 | Milestone-1 intake review | Application Bootstrapping taking more time

### ISSUE THREAD

**Issue by shamb0** [litentry/litentry-app#54]
Application Bootstrapping is taking more time.

**Validation Setup**

| Component | Version |
| --- | --- |
| Release APK | litentry-governance_v1.0.1.apk |
| Android Version | 7.1.1 |
| Litentry Devnet | wss://18.140.130.138 |
| Parity Signer | v4.5.3-beta |

After application launch, getting dashboard is taking more time, 
Sometimes get stuck in the screen with the message 'Connecting to Kusama',

Reboot the app may require for recovery.

![](https://i.imgur.com/T1bklWi.png)

**Comment by ahoseinian** [comment]
fixed previously
