### ISSUE TITLE
Polkadot treasury motion #29 | Milestone-1 intake review | Some minor glitch in text display

### ISSUE THREAD

**Issue by shamb0** [litentry/litentry-app#56]
Some minor glitch in text display, is there any possibility for missing of font support in packaging ?

![](https://i.imgur.com/ggizAtI.png)

**Comment by geastwood** [comment]
Afaik, if the debugger is turned on it will render emoji correctly, however native js engines seem to choke on it.

**Comment by ahoseinian** [comment]
Apparently in contrast with javascript engines running on browsers, rn javascript engine does not have a global `TextDecoder` object. Therefore, `u8aToString` from the package @polkadot/util fails to decode emojis as it is only good for ASCII chars

https://github.com/polkadot-js/common/blob/ec286a57d12b9ba6aab67eed4c258128bed88bf3/packages/x-textdecoder/src/fallback.ts#L4

`fast-text-encoding` package is adding the missing TextDecoder with ability to decode full utf-8 back to the global context
