### ISSUE TITLE
Bug: Modal to select network not displayed correctly with the dark theme

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#572]
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-11-10 at 14 45 05](https://user-images.githubusercontent.com/8374946/141135096-73aaf6ea-f931-4987-ba37-5be96518a2f3.png)

**Comment by ahoseinian** [comment]
Also ![image](https://user-images.githubusercontent.com/1168983/141148389-0b537d65-8b3b-4e0f-9f8a-ba1b36ef8043.png)
