### ISSUE TITLE
Polkadot treasury motion #29 | Milestone-1 intake review | "Treasury" fragment navigation failure

### ISSUE THREAD

**Issue by shamb0** [litentry/litentry-app#58]
Unable to navigate to "Treasury" fragment

After choosing "OK" no response

**Validation Setup**

| Component | Version |
| --- | --- |
| Release APK | litentry-governance_v1.0.1.apk |
| Android Version | 7.1.1 |
| Litentry Devnet | wss://18.140.130.138 |
| Parity Signer | v4.5.3-beta |

**And if possible, pop-up message may be avoided, like in `Tips`, navigation can directly load the `Treasury or Council` screen**

![](https://i.imgur.com/iSJgk1O.png)

**Comment by ahoseinian** [comment]
https://user-images.githubusercontent.com/1168983/120805426-15db2c80-c546-11eb-87ec-0af1fae0fa68.mp4

**Comment by geastwood** [comment]
What about empty state?

**Comment by ahoseinian** [comment]
> What about empty state?

sorry didn't check this before the merge, will add an Activity indicator for loading and an empty message for no data.
