### ISSUE TITLE
Polkadot treasury motion #29 | Milestone-1 intake review | Unable to propose the `Tip`

### ISSUE THREAD

**Issue by shamb0** [litentry/litentry-app#59]
Unable to propose the `Tip`

After choosing "OK" no response

**Validation Setup**

| Component | Version |
| --- | --- |
| Release APK | litentry-governance_v1.0.1.apk |
| Android Version | 7.1.1 |
| Litentry Devnet | wss://18.140.130.138 |
| Parity Signer | v4.5.3-beta |

![](https://i.imgur.com/NtuHl4d.png)

**Comment by geastwood** [comment]
https://wiki.polkadot.network/docs/en/learn-treasury#tipping
