### ISSUE TITLE
Vote for council

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#601]
> As a dot holder I should be able to vote for council election

User can vote up to 16 candidates in the wanted order. The more candidates he votes for, the higher the voting bond.

**Wireframe:**
<img src="https://user-images.githubusercontent.com/85941267/142873435-08715e43-5ccb-4dcd-afc7-735c9aed9bc5.png" width="275" height="575"> <img src="https://user-images.githubusercontent.com/85941267/142873621-252292b4-2b04-4b88-960d-10caf403f46c.png" width="275" height="575">

**Comment by stephanie-olp** [comment]
Tested on iOS and it looks great @ishrak-imam 
I just struggled a bit to close the numeric keyboard after entering the vote value. It seems like it only closes when I tap in the select candidates section

Can we do something there ?

**Comment by geastwood** [comment]
@stephanie-olp @ishrak-imam still relevant?

**Comment by stephanie-olp** [comment]
> @stephanie-olp @ishrak-imam still relevant?

Yes we still have the issue. @ishrak-imam  do you think we can either add a button on the keyboard to confirm the action (e.g: an arrow) or change the logic so when the user clicks anywhere on the module it closes the keyboard ?

**Comment by geastwood** [comment]
This should be done, no?

**Comment by geastwood** [comment]
@litentry/rn-team
