### ISSUE TITLE
Bug: App throws if insufficient fund

### ISSUE THREAD

**Issue by ishrak-imam** [litentry/litentry-app#618]
If an account doesn't have enough fund and user tries to contribute to crowdloan with that account, the app currently throws. The error is not handled.

Following are the list of where this error can potentially happen. We have to check if there are any further cases like this.

- [ ] Coowdloan contribution with account having insufficient funds

**Comment by geastwood** [comment]
@jonalvarezz @bdmason i remember crowdloan webapp has similar issue.

**Comment by jonalvarezz** [comment]
Yes. The tx will naturally fail if there is not enough balance.

From a technical perspective: as Ishrak described, every time there is a user tx, we have to account for these errors being thrown.

Furthermore, from a user perspective, we should inform them what the fees are before the transaction. On the Crowdloan website, we also display a message if the remaining balance after the tx will be less than the Existential Deposit. See: https://github.com/litentry/applications/pull/188

**Comment by stephanie-olp** [comment]
@ishrak-imam any new updates on this issue?

**Comment by ishrak-imam** [comment]
> @ishrak-imam any new updates on this issue?

Although we can make the UX a bit better by informing the account balance to the user before even attempting any action that needs funds but for now we are fine. The crash is a dev only behaviour and in prod it fails with a proper message of insufficient funds. So we can close it now.

**Comment by stephanie-olp** [comment]
Okay thanks let's close it then
