### ISSUE TITLE
Polkadot treasury motion #29 | Milestone-1 intake review | Stability, Connection to mainnet is getting last.

### ISSUE THREAD

**Issue by shamb0** [litentry/litentry-app#62]
Inbetween using the App, connection to mainnet is getting lost, to recover have to reboot the App.
[Could be Stability]

**Validation Setup**

| Component | Version |
| --- | --- |
| Release APK | litentry-governance_v1.0.1.apk |
| Android Version | 7.1.1 |
| Litentry Devnet | wss://18.140.130.138 |
| Parity Signer | v4.5.3-beta |

![](https://i.imgur.com/eB9sEl4.png)

**Comment by ahoseinian** [comment]
https://user-images.githubusercontent.com/1168983/120329850-8b4bc080-c2ec-11eb-8269-6c979e17783c.MP4
