### ISSUE TITLE
Alert Dialog + Button Bar

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#623]
**Alert Dialog**
![image](https://user-images.githubusercontent.com/85941267/143008067-ddbaa76e-1ac8-4833-9837-a8dd692035bc.png)

**Button Bar**
![image](https://user-images.githubusercontent.com/85941267/143008105-bddd9f0b-8a41-41d8-ac17-3b852810ea43.png)

**Comment by stephanie-olp** [comment]
@franjs is that ticket still relevant?

**Comment by silva-fj** [comment]
The library that we are currently using has an implementation for [Dialogs](https://callstack.github.io/react-native-paper/dialog.html), We don't need this anymore.
