### ISSUE TITLE
Receive funds

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#633]
Have the ability to easily share account addresses:
- [ ] Create a new screen "Receive Fund" 
- [ ] Qr Code
- [ ] Share 
- [ ] copy the address
* Wireframe:
When user clicks on the receive funds icon, the following buttom drawer should open: 
![image](https://user-images.githubusercontent.com/85941267/144070382-18bc0156-0c7d-4196-941c-443da8610319.png)

**Comment by geastwood** [comment]
Thank @ahoseinian for having `receive fund` implemented.

How about this account overview page (the one in screenshot) @stephanie-olp? Is it captured in other ticket?

**Comment by stephanie-olp** [comment]
Hi @geastwood Fei, the overview page (which corresponds to the account details screen) is  captured in that ticket : https://github.com/litentry/litentry-app/issues/634
