### ISSUE TITLE
Feature: Calendar Teaser ("Upcoming events" section on the dashboard)

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#639]
> As a user, when I open the app I quickly wanna find out what are the next events in Polkadot/ Kusama governance ecosystem

On the very top of the screen, let's add a section called "Upcoming events":
We can display the next 3 upcoming events on that list
If user clicks on that section he will be redirected to the calendar screen

* Wireframe: 
![image](https://user-images.githubusercontent.com/85941267/143924890-2b421cbe-e0b9-40ac-9f5e-42c5ccb16214.png)

**Comment by ahoseinian** [comment]
on polkadot, It seems there are no calendar apis, what actually is happening is aggregating all possible events in a schedule on the front-end side and show them on calendar page. I don't think doing the same and calling all this apis on the dashboard screen is the best idea. my suggestion is to do it directly on our graphql backend and just use the data coming from that. need to discuss this further with @franjs 

https://github.com/polkadot-js/apps/blob/master/packages/page-calendar/src/useScheduled.ts

**Comment by stephanie-olp** [comment]
Hey @Ekaanth ,
here is the empty state mockup: 
![image](https://user-images.githubusercontent.com/85941267/159280439-ee380953-4150-4211-a848-c0e0a3c0e412.png)

and the icon: 
![Icons](https://user-images.githubusercontent.com/85941267/159280674-90abc104-b114-4092-a9e8-32f2addebdbb.png)

**Comment by stephanie-olp** [comment]
@Ekaanth Hey Abhi, sorry I didn't see that issue earlier but I just noted that there is a misspelling in the title: "calender" instead of "calendar".
Do you think you can take that opportunity to change the whole title of that section to ""Upcoming events" ?

**Comment by Ekaanth** [comment]
@stephanie-olp, Thanks for bringing that to my attention. I have changed the latest PR merge https://github.com/litentry/litentry-app/pull/1035, with the difference in the title to `Upcoming events.`
