### ISSUE TITLE
Add info about registrars 

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#643]
> As a user I want more information about each regristrars to pick one

*** Wireframe**
We have to change the whole identity screen:
![image](https://user-images.githubusercontent.com/85941267/144514549-1d507837-488c-4e0f-9464-17ec55078ff7.png)

When user clicks on "Request judgement" the following bottom drawer opens up:
![image](https://user-images.githubusercontent.com/85941267/144514561-baebf387-fb3b-40c8-b398-d5e191cab304.png)

If user clicks on the information icon, it extend the drawer and information about registers appears in a delimited area. The URL should be clickable
![image](https://user-images.githubusercontent.com/85941267/144514583-936ffd46-4a6f-446a-bd5b-475c987edc7e.png)

* **Copy** :
- For Polkadot :

**Registrar 0:**
URL: https://registrar.web3.foundation/
Fee: 0 DOT

**Registrar 1:**
URL: https://registrar.d11d.net/
Fee: 10 DOT

**Registrar 2:**
URL: https://polkaregistry.org/
Account: 1EpXirnoTimS1SWq52BeYx7sitsusXNGzMyGx8WPujPd1HB,
Fee: 0 DOT

- For Kusama:

**Registrar 0:**
URL: https://registrar.web3.foundation/
Fee: 0.04 KSM

**Registrar 1:**
URL: https://registrar.d11d.net/
Fee: 0.65 KSM

**Registrar 2:**
Fee: 1 KSM

**Registrar 3:**
Fee: 1 KSM

**Registrar 4:**
Fee: 0.04 KSM

**Comment by ishrak-imam** [comment]
@stephanie-olp
Here the url value is not on chain. So we don't have a way to display it for now with going into a hardcoded solution. Which is not ideal.

For now I have added the Fee and Registrar index information.

**Comment by stephanie-olp** [comment]
@ishrak-imam I see, let's do that for now then
