### ISSUE TITLE
Add Empty State to every "no data" screen

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#657]
> As a user, when I see an empty screen I wanna know if it is a bug or there is simply no data to display

The following empty screen has to be implemented everywhere where we have no data to display (eg: no bounties, no motions...). Moreover, it has to replace the current empty state illustration we have on the **My Accounts** screen.
❗️: For screen with Call to Actions, keep the Call to Action underneath the illustration

**The illustration** : 
![image.png](https://images.zenhubusercontent.com/61029ef6db52052cb2a2578a/f7e86025-a21f-491e-a07e-1cf369ec60e6)

**Comment by ishrak-imam** [comment]
<img src=https://user-images.githubusercontent.com/16683923/146351689-8e1e1580-29a2-4b14-ad41-8b79f1943577.png width=250 />

cc @stephanie-olp 
In dark mode the text is not properly visible, since it is part of the image.

**Comment by stephanie-olp** [comment]
@ishrak-imam , I see give me 2 minutes I'll give you the image without the text and we can add the text separately :)

**Comment by stephanie-olp** [comment]
![image](https://user-images.githubusercontent.com/85941267/146352676-d2b225fe-bef4-4b8b-a9e9-2b29faf55e2f.png)
