### ISSUE TITLE
Collect external users email addresses

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#664]
How do we collect the external users email adresses to add them to the external testers list: 
- A google form ? 
- Other ?

**Comment by geastwood** [comment]
Firstly check what TestFlight can provide us, If I remember correctly, we can generate a link, after getting the link user probably will be redirected to a TestFlight page and ask for the email.

**Comment by geastwood** [comment]
AFAIK, has to submit iOS to review and when it passed. The app can be published for external review. However the review process is not that strict.
