### ISSUE TITLE
Report and Suggestion: Lazyload when connecting to the nodes

### ISSUE THREAD

**Issue by hanwencheng** [litentry/litentry-app#667]
Currently, when we connect to the remote node, the "connecting" pages float on the top of the app. 

It happens mostly when 1. first loads the app.  2. switch back to the app. 

But when I do multi-tasks, it is common for me to switch back and forth among my apps. But every time when I switch back I need to wait a while, this is kind of annoying.

So it would be better to keep the existed information in the memory when I switched to some other apps, and update the current page when connected. Probably a "refresh" icon on the top would be enough to indicate we are reconnecting but not a new page to block all the information.

### ⚠️ what do we need?

- [x] UI/UX
- [x] Data Storage in Memory

**Comment by ishrak-imam** [comment]
May be we can remove the api loading screen, now that the api initialization is faster.
@franjs @ahoseinian

**Comment by silva-fj** [comment]
Yeah we could try that for now, at least when coming back to the app (app already in the background). This issue will be gone after we switch to the api proxy
