### ISSUE TITLE
Improvements on export screen

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#713]
As a user, I'm confused about what the password field is used for on the `Export account` screen. The initial impression is that I have to input the password that I chose when creating the account in order to authorize the action for exporting the account. However, I find out, the true use case of the password field is actually to encrypt the content of the exported data.

Therefore I would suggest that we explicitly let the user know about this information. 

And additionally, after successfully exported, the export screen stays unchanged. There is no indication at all, of the result of my action. As a user, I would expect to see a message similar to __Your account is successfully backed up on the device, and encrypted with the password you have specified.__.

Another point is that how can I use the app to import this file, so the account will be imported to the app?

## Next step
* [x] #730
* [x] #731
* [x] Support the function to import account backup json file

**Comment by geastwood** [comment]
If there is anything unclear, feel free to reach out to me.

**Comment by stephanie-olp** [comment]
Further work on #957
