### ISSUE TITLE
Bug: unable to send tx e.g. contribute to crowdloan

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#723]
App version: 0.1.0 68

## Steps To Reproduce

1. navigate to crowdloan screen
2. Tap contribute
3. Select a internal account 
4. FaceID will unlock account, however click unlock has no impact 

Link or media file of the bug:
https://user-images.githubusercontent.com/1623359/146973833-4a1bb554-44a2-46f7-84e4-0e21837c0401.MOV

## The current behavior
Not able to proceed to next step

## The expected behavior
Able to contribute.

**Comment by geastwood** [comment]
is anyone working on this bug? @litentry/rn-team

**Comment by ishrak-imam** [comment]
> is anyone working on this bug? @litentry/rn-team

I think @ahoseinian was working on it, but the problem was not reproducible.

**Comment by ahoseinian** [comment]
@geastwood yes me and @ishrak-imam couldn't reproduce this. also the movie attached to the issue is not playing for some reason.

**Comment by silva-fj** [comment]
I think the issue is related with this [PR](https://github.com/litentry/litentry-app/pull/697). If the account was created before the keychain feature was introduced, it would not be able to retrieve the password. Is that the case @geastwood ?

Are we handling failures when retrieving/storing the passwords @ahoseinian ?

**Comment by ahoseinian** [comment]
yes when retrieving the keychain password is unsuccessful it does nothing and let the user put their password.

**Comment by silva-fj** [comment]
We should probably add a flash message or Snackbar or just an error message in the form to tell the user the password could not be retrieved or something and that he/she needs to enter the password manually

**Comment by geastwood** [comment]
I think the password is correctly retrieved yeh still can not proceed. I.e. submit contribution.

**Comment by geastwood** [comment]
> @geastwood yes me and @ishrak-imam couldn't reproduce this. also the movie attached to the issue is not playing for some reason.

Ok, I will check it again from my side.

**Comment by geastwood** [comment]
Can close now.

Re-imported the account and now can submit the tx.
