### ISSUE TITLE
Add a relative date of each tip in tips list view

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#754]
As a user it's hard for me to figure out when is the tip in tips overview screen is being proposed. 

## proposed solution 

Add a relative date, e.g. 2 hours ago to each tip in tips list view.

**Comment by geastwood** [comment]
Let's plan this in.

**Comment by silva-fj** [comment]
We can't get this info from the polkadot api (`query.tips`), we need to index the tips to have this data. We can listen to the `NewTip` event to get the block number and date the the tip was created.

**Comment by stephanie-olp** [comment]
Before working on this ticket we have to:
* Test that tips indexing is working
* Verify that the indexer is production-ready 
* Update the resolver

**Comment by ishrak-imam** [comment]
Done! [here](https://github.com/litentry/litentry-app/pull/1131)
