### ISSUE TITLE
Bug: android send feedback error

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#820]
App version:

## Steps To Reproduce

1.
2.

Link or media file of the bug:

**Comment by ghost** [comment]
https://images.zenhubusercontent.com/315463277/7987990c-fec6-40d7-bbc6-fd4168378a4f/22_01_27_09_42_57.mp4

**Comment by stephanie-olp** [comment]
Duplication of https://github.com/litentry/litentry-app/issues/819
