### ISSUE TITLE
Polka assembly discussion not clickable 

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#821]
![Screenshot 2022-01-27 at 10.56.27.png](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/8266d607-bab8-4149-80ad-d67bf0fa7ced)

**Comment by ghost** [comment]
You cannot click links and I never manage to link my account with litentry app therefore making this segment useless. 
I would love to be able to click on the links and be able to comment here as well

**Comment by stephanie-olp** [comment]
Indeed the user can only see the discussion and the comments, if he wants to realize any action he's redirected to the Polkassembly website. But we are planning on working on it, see: https://app.zenhub.com/workspaces/rn-apps-team-6102625c8c60d60015b94e18/issues/litentry/litentry-app/544
