### ISSUE TITLE
Layout misalignment

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#822]
![Screenshot 2022-01-27 at 10.56.12.png](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/1eb2c80b-7dc0-4356-a700-e6c8e754e5ee)

**Comment by Ekaanth** [comment]
The issue has been fixed, PFA
![Screenshot_1644333738](https://user-images.githubusercontent.com/22363352/153018439-546487d2-8d6a-4672-be7b-9765fa15383e.png)
