### ISSUE TITLE
Top padding in overview section

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#823]
![Screenshot 2022-01-27 at 10.55.58.png](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/bd76e38e-512f-4b0c-96a1-364ec1466d71)

**Comment by Ekaanth** [comment]
Hi, @mikuczi. Can if you're still getting this issue, since I'm unable to reproduce that issue on a smaller screen, I see an alignment issue with the contribution on the smaller screen. I'll be working to fix it.

**Comment by Ekaanth** [comment]
Unable to reproduce this issue with white padding line

![Simulator Screen Shot - iPhone 12 - 2022-02-17 at 09 56 24](https://user-images.githubusercontent.com/22363352/154440670-800f0454-455b-4fa8-858a-1af35064be19.png)
