### ISSUE TITLE
cannot link polkassembly account with litentry discussion in app

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#825]
ok I just read that this will be future development.
Is that correct? ![Screenshot 2022-01-27 at 14.27.42.png](https://images.zenhubusercontent.com/61e6dbe5f12699478a956bb0/9adf4f76-9672-4d45-92e4-5e81ab4e608f)

**Comment by stephanie-olp** [comment]
Will be fixed with : https://app.zenhub.com/workspaces/rn-apps-team-6102625c8c60d60015b94e18/issues/litentry/litentry-app/544
