### ISSUE TITLE
Bug: Unable to send funds with decimals

### ISSUE THREAD

**Issue by silva-fj** [litentry/litentry-app#837]
As a user I would like to be able to send fractions of funds from my wallet. When trying to add `,` it gets deleted automatically.
Link or media file of the bug:

![File](https://user-images.githubusercontent.com/8374946/152359870-7599ffa9-d4b4-48d5-af1c-a3d430cf88e2.jpg)

## The current behavior
Currently only integer numbers can be added in the amount.

## The expected behavior
One should be able to send fractions of funds (e.g: 0.25)

**Comment by Ekaanth** [comment]
@franjs , can you verify if the issue still exists? Since I'm not able to reproduce the problem. Instead, I see a correct working numbering system.

![Screenshot_1644509381](https://user-images.githubusercontent.com/22363352/153448505-55bbb699-ab1e-441f-963d-75a450936872.png)

**Comment by silva-fj** [comment]
> @franjs , can you verify if the issue still exists? Since I'm not able to reproduce the problem. Instead, I see a correct working numbering system.

@Ekaanth Yes, it is still an issue. I just found out that it happens only on IOS, we have to change the `keyboardType` of the `TextInput`. The issue is that the current type only allows adding comma (,) for decimals which is invalid
