### ISSUE TITLE
Research : Conviction Voting

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#861]
> A significant [change](https://github.com/paritytech/substrate/pull/10195) of demoncracy is merged into Substrate, it is yet to be implemented on Kusama/Polkadot, but it will definitely be there one day.

 So let's start to look into how to translate conviction voting into our app: if we are the first one to do it, it will help us to stand out from the other products
- [ ] Read about Conviction Voting :
https://medium.com/giveth/conviction-voting-a-novel-continuous-decision-making-alternative-to-governance-aa746cfb9475

- [ ] If Conviction Voting is implemented in Polkadot, how would the current system change? What differences would it make?
https://github.com/paritytech/substrate/pull/10195

- [ ] What would be the most suitable way to incorporate this change into our app ?

**Comment by stephanie-olp** [comment]
https://www.notion.so/litentry/Conviction-Voting-97fccb6e984042018e01ff53566f0597

**Comment by hanwencheng** [comment]
Please also make sure we support this feature when Polkadot launched it. I am contacting the Parity team in the Builder channel.
