### ISSUE TITLE
Side Menu freeze on wrong button

### ISSUE THREAD

**Issue by ghost** [litentry/litentry-app#878]

**Comment by mikuczi** [comment]
[Uploading... 22-02-16-09-51-25.mp4]

**Comment by ghost** [comment]
Android system going back is not triggering menu to jump to the right tab. 
It is really minor but I just noticed it

**Comment by ghost** [comment]
On IOS is fine.

**Comment by mikuczi** [comment]
https://images.zenhubusercontent.com/315463277/0d1bb5b4-322d-4394-8c41-7e469f0f6ff8/22_02_16_09_51_25.mp4https://images.zenhubusercontent.com/315463277/681bb6a7-7b7f-49e4-8bbc-40aa849ff16a/22_02_16_09_51_25.mp4

**Comment by ghost** [comment]
https://images.zenhubusercontent.com/315463277/74a8bc11-6702-49eb-9d50-839573b1643d/22_02_16_09_51_25.mp4
