### ISSUE TITLE
Bug: No tippers shouldn't shop rendering Tip detail page

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#940]
If there is no tippers, currently we only display an empty state of "There is no tippers yet". We are not displaying tip's details, such from whom, and description of the tip.

App version:

## Steps To Reproduce

1. Go to a tip detail where there is no tipper yet

Link or media file of the bug:

https://user-images.githubusercontent.com/1623359/156322965-e2575651-d0ec-4c65-9ae1-65fcdea2eafc.MP4

## The current behavior
Currently we only display empty state for the whole screen.

## The expected behavior

If there is no tipper, we should still display tip's detail such as "who", or "Finder" plus the "Reason"

**Comment by silva-fj** [comment]
Thanks for reporting this issue @geastwood. The problem is actually a braking change in the litentry-graph, making this screen not to get any data.

**Comment by geastwood** [comment]
Ah, good to know, ty. 🙇
