### ISSUE TITLE
Running `lint` npm target produce a lot of change

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#95]
Is there any change recently caused this?

It seems `eslint` is triggering a lot of `prettier` formatting.

**Comment by ahoseinian** [comment]
yes my bad, I have changed `printWidth`: 120 from 80. forgot to mention it. is that ok?

**Comment by silva-fj** [comment]
I personally don't have a strong opinion.. I generally use 80 which is prettier's default because It fits better when doing vertical splits on the editor, but I don't mind using 120

**Comment by geastwood** [comment]
Ok, let's settle on **120**, will create PR.
