### ISSUE TITLE
Add support to Polkadot JSON files (Spike)

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#957]
Currently we don't support importing accounts (JSON files) exported from the polkadotjs app. This is because we cannot use polkadot's `Keyring`. We are currently using `react-native-substrate-sign` which uses a different algorithm to decrypt the json file.

**Comment by silva-fj** [comment]
it would not be feasible to add support for this in the library that we are using (react-native-substrate-sign). It has too many issues, it does not even compile. 

But the only wasm function polkadot's Keyring is using for importing accounts from JSON files is `blake2b` (used for the `checkAddressChecksum` function), we can wait until the crypto library we are sponsoring is ready to use it in the `Keyring` instead.
